### ISSUE TITLE
AdGuard settings window appears on the startup

### ISSUE THREAD

**Issue by riddy-p** [AdguardTeam/AdGuardMiniForMac#1018]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.13

### Environment

```markdown
- OS:Sequoia 15.0
- Safari version: 18.0
```

### Issue Details

Steps to reproduce:
1. Login to macOS account from sleep, power on, or restart
2. AdGuard settings window opens up on its own
3.

### Expected Behavior

AdGuard settings window should not immediately appear and open on its own when logging in

### Actual Behavior

Settings window keeps opening on its own when logging in

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@riddy-p, hello! Please update AdGuard for Safari to latest 1.11.19 version and check if the problem persists.

**Comment by riddy-p** [comment]
Hello, the issue was persistent across previous versions of AdGuard too but having now updated it to 1.11.19, it seems to have fixed it. Thank you!
