### ISSUE TITLE
The recent update broke AdGuard

### ISSUE THREAD

**Issue by julian-weinert** [AdguardTeam/AdGuardMiniForMac#1019]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.19 (build 335, CT 2.0.44)

### Environment

```markdown
- OS:Mojave 10.14.5
- Safari version: 14.1.2 (14611.3.10.1.7)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

Steps to reproduce:
1. Install AdGuard
2. Enable extension in Safari

### Actual Behavior

Since the last update from yesterday AdGuard is broken. When I enable the extension the additional extensions don't appear anymore. The toolbar icon appears and disappears a few times before it gives up.
The app claims the extension isn't activated.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot 2024-09-18 at 23 31 41](https://github.com/user-attachments/assets/f816aff0-cb49-4f43-82cf-34dc46280949)

</details>

<details><summary>Screencap 1:</summary>

![Screencap 1](https://github.com/user-attachments/assets/f971e0da-57de-45b0-8901-e757fd93217d)

</details>

<details><summary>Screencap 2</summary>

![Screencap 2](https://github.com/user-attachments/assets/21f162c4-d8d1-405b-8800-2ff2311b5cea)

</details>

### Additional Information

I tried old versions of AdGuard, none of them work. They all exhibit the same strange behaviour. Nothing else changed on my computer, I didn't update anything else, not Safari (a surprise running Mojave...) or anything.
I installed the AdGuard update and suddenly the extension stopped working and disappeared in the front of my eyes.

**Comment by alexx7311** [comment]
@julian-weinert, hello! Please disable all other extensions in Safari and try completely uninstalling AdGuard for Safari:

1. Uncheck all AdGuard for Safari extensions in `Safari - Preferences - Extensions`
2. Remove AdGuard for Safari application from Applications folder
3. In Finder press Shift+Command+G and remove following files:
- Remove **AdGuardSafariApp** folder from `~/Library/Application` Support directory
- Remove from `~/Library/Application Scripts` - all directories started with **com.adguard.safari** and **TC3Q7MAJXF.com.adguard.safari.AdGuard** folder
- Remove from `~/Library/Containers` - all directories started with **AdGuard-**
- Remove **TC3Q7MAJXF.com.adguard.safari.AdGuard** folder from `~/Library/GroupContainers` directory
- Remove **com.adguard.safari.AdGuard.plist** from `~/Library/Preferences`
4. Quit all `AdGuard` and `cfprefsd` processes from Activity monitor
5. Quit Safari.
6. Reinstall AdGuard for Safari
