### ISSUE TITLE
Unable to launch AdGuard assistant due to Content Security Policy

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardMiniForMac#1034]
### AdGuard version

Version 1.11.20 (build 341, CT 2.0.44)

### Environment

```markdown
- OS: 15.1 (24B83)
- Safari version: Version 18.1 (20619.2.8.11.10)
```

### Issue Details

Steps to reproduce:
1. Visit reddit.com
2. Click on AdGuard extension button
3. Click 'Select' next to Block an element

### Expected Behavior

AdGuard assistant window appears.

### Actual Behavior

Nothing appears.

### Additional Information

Looking at the console, the following errors appear:

```
[Error] Refused to load safari-extension://A47A7AAF-B5D9-4116-9938-20C9B1D0547D/assistant.embedded.js because it does not appear in the script-src directive of the Content Security Policy.
[Error] Refused to load safari-extension://A47A7AAF-B5D9-4116-9938-20C9B1D0547D/assistant.runner.js because it does not appear in the script-src directive of the Content Security Policy.
```

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/AdguardAssistant/issues/419
