### ISSUE TITLE
Add Dark Mode support

### ISSUE THREAD

**Issue by kinoute** [AdguardTeam/AdGuardMiniForMac#120]

**Comment by F3000** [comment]
Any progress here ?

**Comment by QuarterSwede** [comment]
Looking for the same. Mainly care about the menubar icon that is dark on dark.

**Comment by tvinzz** [comment]
@QuarterSwede, the problem with icon is fixed in Electron 8.3.3. https://github.com/AdguardTeam/AdGuardForSafari/issues/286
