### ISSUE TITLE
Remove Obsolete Filters

### ISSUE THREAD

**Issue by BranchS** [AdguardTeam/AdGuardMiniForMac#134]
As mentioned in issue #93 the Safari-Optimized filter is obsolete, and should be removed. I'm pulling this out into its own issue, so it doesn't get lost in the shuffle, and also to pose the question: are there any other obsolete filters that should be removed?

**Comment by ameshkov** [comment]
@BranchS makes sense, thank you!

> are there any other obsolete filters that should be removed?

Well, we would like not to remove them, but to replace them with new filters. We are slowly doing it already.

**Comment by BranchS** [comment]
That sounds good! I'm gonna push again for some sort of AdGuard Malware & Security Filter... at least just a combination of the three existing ones to allow only one checkbox.

**Comment by BranchS** [comment]
Is there any update on this (removing obsolete filters)? And/or creating an AdGuard Malware & Security Filter (as it's the only category without an official AdGuard filter).

**Comment by BranchS** [comment]
@ameshkov any update on this? Removing the obsolete Safari filter and potentially creating an AdGuard Malware & Security Filter (as it's the only category without an official AdGuard filter)

**Comment by BranchS** [comment]
> @ameshkov any update on this? Removing the obsolete Safari filter and potentially creating an AdGuard Malware & Security Filter (as it's the only category without an official AdGuard filter)

@ameshkov @Mizzick any update on this? thanks :)

**Comment by ameshkov** [comment]
@BranchS not yet. The only prerequisite to removing the Safari filter is updating AdGuard Pro for iOS which enables it by default. This will be done in a couple of months.
