### ISSUE TITLE
Add an option - open the application minimized.

### ISSUE THREAD

**Issue by IFierta** [AdguardTeam/AdGuardMiniForMac#264]
Add an option - open the application minimized. So that when starting the application manually, a window does not appear.

**Comment by BigTimeStats** [comment]
First of all thank you for the application. Is there any possibility of not having to run the application for it to work in safari, like in the background without an app having to be open?

**Comment by Mizzick** [comment]
@BigTimeStats 
It is not necessary to have the app open all the time, it could be closed and you will still have ads blocked in Safari. 
But it would not be possible to update filters and use assistant then.

**Comment by Mizzick** [comment]
@IFierta Thanks for an idea, we will consider this.

**Comment by superlex** [comment]
I agree :)
A reason for opening AG for Safari app is to update filters or use assistant (see https://github.com/AdguardTeam/AdGuardForSafari/issues/264#issuecomment-535969422), but you don't need the window to do that (for example you can use the icon in the menubar to update filters), so it will be more distraction free if window doesn't appear.

**Comment by BigTimeStats** [comment]
> @BigTimeStats
> It is not necessary to have the app open all the time, it could be closed and you will still have ads blocked in Safari.
> But it would not be possible to update filters and use assistant then.

Thanks for the response. When I close the application, I get this in the safari toolbar: 
<img width="240" alt="image" src="https://user-images.githubusercontent.com/29850965/65826824-3bc41000-e240-11e9-8888-41bf668a7494.png">

**Comment by ameshkov** [comment]
@BigTimeStats 

> Thanks for the response. When I close the application, I get this in the safari toolbar:

The text is misleading. Content blocking actually works, but you need to run the app in order to change settings (disable or enable AG on a website for instance).

**Comment by midco** [comment]
Is there a reason why adguard can not be user defined to only open in active browser?  That would stop the loading of the the huge white adguard screen every time one wakes up their devise.  It would be more user friendly - and seemingly wiser that current mode :)
Thanks!

**Comment by ameshkov** [comment]
> That would stop the loading of the the huge white adguard screen every time one wakes up their devise

Most likely, the reason for this issue is that not all AdGuard Safari extensions are enabled, and it will be fixed in v1.6.

If you have all extensions enabled and it still opens at login, please share your log file with us:
https://github.com/AdguardTeam/AdGuardForSafari/issues/204#issuecomment-537037434

**Comment by chimit** [comment]
+1 for the option to start AdGuard minimized.

Moreover, is it possible to start AdGuard only when Safari is started?

**Comment by frederickjjoubert** [comment]
Any update on this? +1 for starting AdGuard minimized please.

**Comment by Versty** [comment]
@frederickjjoubert 
Will be fixed very soon, you can track the progress or discuss in #805.
