### ISSUE TITLE
Error in display flograppling.com

### ISSUE THREAD

**Issue by jasonlakez** [AdguardTeam/AdGuardMiniForMac#341]
When I open https://www.flograppling.com with the general filter extension enabled, it won't be displayed correctly.

Only the extension, even without any filter list.

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/35470714/79070181-5de82180-7caa-11ea-94d7-0af2cc4409d3.png">

macOS Catalina 10.15.4
AdGuard for Safari Version 1.7.4

**Comment by Oleg-Chashko** [comment]
**jasonlakez**
• AdGuard for Safari version: 1.7.4
• Environment name and version: Safari 13.1 (15609.1.20.111.8)
• Operating System: macOS 10.15.4 (19E266)
• Filters you use in AdGuard: AdGuard Base Filter, Annoyances filter, AdGuard Deutscher Filter, AdGuard Russischer Filter.

**The site is opening, I have no problem opening.**
<img width="854" alt="Bildschirmfoto 2020-04-12 um 21 55 36" src="https://user-images.githubusercontent.com/62497891/79078453-cd8cf980-7d08-11ea-9a85-d8f82ebe41f6.png">

**Comment by jasonlakez** [comment]
> **jasonlakez**
> • AdGuard for Safari v.1.7.4
> • Safari 13.1 (15609.1.20.111.8)
> • macOS 10.15.4 (19E266)
> • Filters you use in AdGuard: AdGuard Base Filter, Annoyances filter, AdGuard Deutscher Filter, AdGuard Russischer Filter.
> 
> **The site is opening, I have no problem opening.**
> <img alt="Bildschirmfoto 2020-04-12 um 21 55 36" width="854" src="https://user-images.githubusercontent.com/62497891/79078453-cd8cf980-7d08-11ea-9a85-d8f82ebe41f6.png">

Thanks, I solved the problem by reducing the amount of lists
