### ISSUE TITLE
JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardMiniForMac#359]
Version of AdGuard for Safari: 1.8 Beta
When switching from a light theme to a dark theme.
An error occurs: A JavaScript error occurred in the main process.
<img width="418" alt="A JavaScript error occurred in the main process" src="https://user-images.githubusercontent.com/62497891/89214189-a499b880-d5c6-11ea-9390-3fbed51952cb.png">
[log.log.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5017615/log.log.zip)
[adg_safari_logs_1596480050403.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5017751/adg_safari_logs_1596480050403.zip)

**Comment by Oleg-Chashko** [comment]
[AdvancedBlocking_2020-08-03-210239_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5023206/AdvancedBlocking_2020-08-03-210239_MacBook-Pro.crash.zip)

**Comment by tvinzz** [comment]
@Oleg-Chashko, thanks for your report, it's fixed and will be available with next beta

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko, thanks for your report, it's fixed and will be available with next beta

I am glad to help.
