### ISSUE TITLE
Failed to load resource: The file “scriptlets.js.map” couldn’t be opened because there is no such file.

### ISSUE THREAD

**Issue by tempissue** [AdguardTeam/AdGuardMiniForMac#365]
Similar to issue #287, I'm getting this error in my console again.

Safari 13.1.2
AdGuard for Safari 1.8 beta

**Comment by andrewspear** [comment]
Same for me but I'm using AdGuard 1.8.2 and Safari 14.0

**Comment by zzebrum** [comment]
dup of #377. will be fixed in the next version
