### ISSUE TITLE
Console error "scriptlets.js.map not found"

### ISSUE THREAD

**Issue by freinbichler** [AdguardTeam/AdGuardMiniForMac#377]
### Issue Details

* AdGuard for Safari version: 1.8.2
* Environment name and version: Safari 13.1.2 (15609.3.5.1.3)
* Operating System: macOS 10.15.6
* Filters you use in AdGuard: Ad Blocking, Privacy
* Any other browser extensions you have installed: 1Password, JSON Peep

### Expected Behavior
no console errors

### Actual Behavior
In the Safari dev tools "Console" tab, the following error is shown:
`Failed to load resource: The file “scriptlets.js.map” couldn’t be opened because there is no such file. safari-extension://523679BF-9975-4F60-AA52-C4DFF501648D/b109a5c9/scriptlets.js.map`

### Screenshots

<details><summary>Screenshot:</summary>

<img width="1771" alt="Screenshot 2020-08-25 at 11 45 19" src="https://user-images.githubusercontent.com/118223/91159558-835d5100-e6c8-11ea-9520-ee426d2fe97d.png">

</details>

**Comment by Elshir** [comment]
same here!

**Comment by vozersky** [comment]
fixed in 1.8.3 beta

**Comment by glyph** [comment]
Just curious - when will 1.8.3 be released? I am seeing this on 1.8.2 as well.

**Comment by gasedwards** [comment]
Me too.

**Comment by glyph** [comment]
As a web developer it's really annoying to see this every time I open my console to check on what's going on.  I checked https://adguard.com/en/adguard-safari/overview.html and even the direct-download version is still only 1.8.2. Can you release an update please?

**Comment by tvinzz** [comment]
fixed in v1.8.3-beta https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.8.3-beta
