### ISSUE TITLE
Full screen content after blocking ad elements in some websites

### ISSUE THREAD

**Issue by cmutinda** [AdguardTeam/AdGuardMiniForMac#378]
<img width="1440" alt="Screen Shot 2020-08-25 at 18 03 18_WITHOUT_BLOCKING" src="https://user-images.githubusercontent.com/20986977/91192043-28465100-e6fe-11ea-89c2-fbae9f920eea.png">

Page without blocking element

<img width="1418" alt="Screen Shot 2020-08-25 at 18 05 17_WITH_BLOCKING" src="https://user-images.githubusercontent.com/20986977/91192053-2da39b80-e6fe-11ea-8bc8-32a94d3b5802.png">

Page after blocking element

<img width="1438" alt="Screen Shot 2020-08-25 at 18 06 52_ON_CHROME" src="https://user-images.githubusercontent.com/20986977/91192059-2ed4c880-e6fe-11ea-9b45-f32e9b4c67b3.png">

Page on chrome after blocking element

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ Yes] I am running the latest version
- [ Yes] I checked the documentation and found no answer
- [ Yes] I checked to make sure that this issue has not already been filed

### Problem Description
AdGuard is unable to completely eliminate the whitespace left after blocking the elements of an ad for example using Microsoft Outlook's Web App

### Proposed Solution
I would propose that a feature be built to ensure that the web pages maximize the space left after blocking elements like other ad blockers work on browsers like chrome

**Comment by tvinzz** [comment]
@cmutinda, can you please provide a screenshot

**Comment by cmutinda** [comment]
> @cmutinda, can you please provide a screenshot
I've updated the feature request with a screenshot

**Comment by tvinzz** [comment]
@cmutinda, please try to select bigger size of blocking element:
![image](https://user-images.githubusercontent.com/15062885/93146505-aee7c000-f6f7-11ea-833a-b7050978af94.png)

the result is:
![image](https://user-images.githubusercontent.com/15062885/93146530-c030cc80-f6f7-11ea-81f2-a6fea24791f7.png)
