### ISSUE TITLE
Update the app icon to match Big Sur guidelines

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardMiniForMac#413]
Not sure why we still haven't done this.

**Comment by Oleg-Chashko** [comment]
@ameshkov 
And please don't forget the "Block element on page" window. Round the corners of the window and buttons.
<img width="679" alt="Block element on page" src="https://user-images.githubusercontent.com/62497891/99184757-7db25d00-2745-11eb-8c37-b2e2f7f7f821.png">
