### ISSUE TITLE
Update the app "Block an element" window to match Big Sur guidelines

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardMiniForMac#414]
Round the corners of the window and buttons. Move the window close button to the left side. Same color tone as your slider-buttons. Also, make a dark theme.
**Example:**
<img width="155" alt="Bildschirmfoto 2020-11-15 um 13 34 44" src="https://user-images.githubusercontent.com/62497891/99185339-65444180-2749-11eb-8c26-92c2a6926ff6.png">

---------------------------------------------------------------------------------------------------------------------
<img width="679" alt="99184757-7db25d00-2745-11eb-8c37-b2e2f7f7f821" src="https://user-images.githubusercontent.com/62497891/99185353-83aa3d00-2749-11eb-8367-924f3c2c7383.png">

**Comment by ameshkov** [comment]
We can't fully match Big Sur here since this is a Javascript library that we use in all AG products (not just MacOS).
