### ISSUE TITLE
Scriptlets + Cosmetic rules aren't applied

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardMiniForMac#421]
See the discussion here:
https://github.com/AdguardTeam/AdGuardForSafari/issues/420

Add these two rules to the user filter:
```
example.org##body
example.org#%#alert('1');
```

Expected: body on example.org is hidden
Actual result: nothing is hidden

**Comment by Oleg-Chashko** [comment]
@ameshkov 
Please pay attention, maybe these problems are related?

<img width="866" alt="Bildschirmfoto 2020-11-17 um 16 10 29" src="https://user-images.githubusercontent.com/62497891/99407484-716a0380-28ef-11eb-9ece-0f81a286b363.png">

kitguru.net #67403
Rule doesn't work in 1.8.5 #404

**Comment by ameshkov** [comment]
Yeah, I think they all are related

**Comment by ameshkov** [comment]
@Oleg-Chashko the fix is available in 1.8.6 beta already

**Comment by superlex** [comment]
> @Oleg-Chashko the fix is available in 1.8.6 beta already

Yep, just updated, thank you!
