### ISSUE TITLE
UI Fix for AdGuard for Safari v.1.8.6 Release

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardMiniForMac#424]
Please correct the inaccuracies in the user interface.
**Example:**
<img width="989" alt="OK - Benutzerregeln" src="https://user-images.githubusercontent.com/62497891/99549189-ae023180-29b9-11eb-8bf1-ad13e67ae071.png">

<img width="989" alt="Positivliste" src="https://user-images.githubusercontent.com/62497891/99549212-b35f7c00-29b9-11eb-810e-66f51e946d7f.png">

--------------------------------------------------------------------------------------------------------------------------
**Example:**
<img width="1031" alt="OK" src="https://user-images.githubusercontent.com/62497891/99549339-d427d180-29b9-11eb-849b-f7636bb6e529.png">

<img width="1024" alt="Allgemein" src="https://user-images.githubusercontent.com/62497891/99549364-dbe77600-29b9-11eb-8809-eb849f9574c5.png">

--------------------------------------------------------------------------------------------------------------------------
**_Thank you for your work!_**

**Comment by Oleg-Chashko** [comment]
Please correct the color of the letters in the text.
<img width="378" alt="ok" src="https://user-images.githubusercontent.com/62497891/99755705-bb1f3d80-2aeb-11eb-95d0-a02a6a9f9689.png">
<img width="378" alt="Not ok" src="https://user-images.githubusercontent.com/62497891/99755710-beb2c480-2aeb-11eb-8c54-d81142d499a3.png">

**Comment by Oleg-Chashko** [comment]
Please correct, the watering can is not horizontally centered.

![Bildschirmaufnahme 2020-11-20 um 15 09 56](https://user-images.githubusercontent.com/62497891/99810541-285ebd00-2b44-11eb-8b03-8b4419494ec5.gif)

**Comment by Oleg-Chashko** [comment]
Please correct, the spacing between buttons is the same throughout the application.

![Bildschirmfoto 2020-11-20 um 15 44](https://user-images.githubusercontent.com/62497891/99815396-84c4db00-2b4a-11eb-9a3e-f07bdfd70f0b.jpg)

**Comment by Oleg-Chashko** [comment]
**The problem is not solved!**
<img width="569" alt="Bildschirmfoto 2020-11-25 um 20 35 30" src="https://user-images.githubusercontent.com/62497891/100274065-1921aa00-2f5e-11eb-834e-f4f5f2f81c31.png">
The button frame should be green. See example:
**Example:**
<img width="188" alt="99833877-03c60d80-2b63-11eb-946b-36899654db0b" src="https://user-images.githubusercontent.com/62497891/100274104-2a6ab680-2f5e-11eb-9900-1cee48058b06.png">

**Comment by tvinzz** [comment]
> **The problem is not solved to v.1.8.7 Beta!**
1. This is not a 'problem'. The color of this button is correct.
Our design team is preparing new design for future release.
2. This icon is centered. It's just not symmetric.

**Comment by Oleg-Chashko** [comment]
> > **The problem is not solved to v.1.8.7 Beta!**
> 
> 1. This is not a 'problem'. The color of this button is correct.
>    Our design team is preparing new design for future release.
> 2. This icon is centered. It's just not symmetric.

@tvinzz 
1. ok
2. I wrote about the funnel and the little green bar, not the icon. I know that the icon is horizontally centered.

**Comment by tvinzz** [comment]
@Oleg-Chashko, this is svg icon and it's centered.
