### ISSUE TITLE
Revamp Big Sur style icon

### ISSUE THREAD

**Issue by anonyme123** [AdguardTeam/AdGuardMiniForMac#425]
The new app icon for Big Sur is very ugly in my opinion. It is also slightly **too big** compared to other Apple system apps. 

You can see that in the dock where the icon is next to other app icons:
<img width="256" alt="Screenshot 2020-11-19 at 11 36 54" src="https://user-images.githubusercontent.com/19681420/99655127-97acb200-2a5b-11eb-9bfb-78f1a9c40779.png">

[Here](https://firebasestorage.googleapis.com/v0/b/macos-icons.appspot.com/o/icons_approved%2FAdGuard.icns?alt=media&token=74f91e44-ba8f-463f-8c70-6ddbbd51d8fe) is an example of a clean, good looking, correctly sized icon:

![AdGuard_256x256x32](https://user-images.githubusercontent.com/19681420/99654784-1e14c400-2a5b-11eb-9a11-28648781667c.png)

The current icon for comparison:
![app-icon-256](https://user-images.githubusercontent.com/19681420/99655006-71871200-2a5b-11eb-89b8-79514da497c0.png)

**Comment by vozersky** [comment]
On it, we are fixing the oversize icon in the next build

**Comment by superlex** [comment]
Hello, I agree, it's too big but it's "old style" too.
We need something iOS-like, as anonyme123 suggested, but with some depth effects, as Safari icon:
https://cdn.arstechnica.net/wp-content/uploads/2020/11/Screen-Shot-2020-11-12-at-2.16.58-AM.jpg

**Comment by ddddxxx** [comment]
System icons are 824/1024 px FYI. The current AdGuard icon is 954/1024 px and not even pixel perfect.

**Comment by tmonsores** [comment]
I will provide the fix while the app does not get updated. Just use the icon for the Adguard paid version. They prepared a beautiful and Big Sur compliant icon for it.

<img width="233" alt="Screen Shot 2020-11-20 at 12 16 27" src="https://user-images.githubusercontent.com/13514961/99817391-9cd93200-2b2b-11eb-98b8-560d10b9fc50.png">

[AppIcon.icns.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5574410/AppIcon.icns.zip)

**Comment by ciaw** [comment]
I was so hoping this icon change was a mistake. 

It used to be so clean and modern looking, and now is so old fashioned and ugly looking. 😢

**Comment by ameshkov** [comment]
Worry not, we'll update it in the next update (soon)

**Comment by SamAkc** [comment]
I can deeply recommend octaviotti's icon on https://macosicons.com, which looks super suitable and clean for Big Sur's design language. I put it in the attachment as a preview. All credits go of course to @octaviotti and @el_rumo 's repository on GitHub for Big Sur icon replacements.


<img width="739" alt="Bildschirmfoto 2020-11-23 um 10 39 12" src="https://user-images.githubusercontent.com/48156679/99947335-21b88b80-2d78-11eb-92c0-6a904722ded1.png">

**Comment by superlex** [comment]
https://github.com/AdguardTeam/AdGuardForSafari/commit/9cb86f6628d46ea60a6de6b71ef742b49161aee0
:D

**Comment by Oleg-Chashko** [comment]
https://github.com/AdguardTeam/AdGuardForSafari/commit/9cb86f6628d46ea60a6de6b71ef742b49161aee0 :(

**Comment by Oleg-Chashko** [comment]
I think this looks better.
![AppIcon](https://user-images.githubusercontent.com/62497891/100104947-155f2c00-2e67-11eb-98ba-14106bdee44c.jpg)
 _But you know better._

**Comment by Oleg-Chashko** [comment]
Thank you so much. Now you have done beautifully!
![app-icon-128@2x](https://user-images.githubusercontent.com/62497891/100218357-f15a2400-2f14-11eb-84ad-dbe206d06515.png)
https://github.com/AdguardTeam/AdGuardForSafari/commit/3132abd

**Comment by superlex** [comment]
Very very nice, good work :)
