### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by xenofont1** [AdguardTeam/AdGuardMiniForMac#431]
### Issue Details

* AdGuard for Safari version: 1.8.6
* Environment name and version: 13.1.2 (13609.3.5.1.5)
* Operating System: 10.13.6 (17G14033)
* Filters you use in AdGuard: AdGuard General ONLY (the rest it says are disabled in Safari)
* Any other browser extensions you have installed: None

### Expected Behavior
It should not display this message
### Actual Behavior
A JavaScript error occurred in the main process

Uncaught Exception:
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)

**Comment by xenofont1** [comment]
![javascript error](https://user-images.githubusercontent.com/74800747/99863169-eb59f100-2b6a-11eb-96ed-2da8130a1e91.png)

**Comment by TheHasagi** [comment]
Duplicate, related issue #419
