### ISSUE TITLE
"Compilation failed"

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardMiniForMac#434]
AdGuard for Safari version: 1.8.6 Release
Environment name and version: Safari v.14.0.1 (16610.2.11.51.8)
Operating System: macOS Big Sur v.11.0.1 (20B29)

[adg_safari_logs_1605996346255.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5578490/adg_safari_logs_1605996346255.zip)

<img width="1022" alt="Bildschirmfoto 2020-11-21 um 22 37 23" src="https://user-images.githubusercontent.com/62497891/99888108-5af2dd80-2c4a-11eb-8fe8-451c2db17841.png">

**Comment by Oleg-Chashko** [comment]
Restarting AdGuard for Safari helped.

**Comment by superlex** [comment]
See https://github.com/AdguardTeam/AdGuardForSafari/issues/429

**Comment by Oleg-Chashko** [comment]
@ameshkov 
The problem appears when starting the application. Easily achieved with the test: AdGuard for Safari - Pause 15sec

<img width="1022" alt="Bildschirmfoto 2020-11-23 um 08 26 18" src="https://user-images.githubusercontent.com/62497891/99938060-57a14400-2d67-11eb-94a2-e7ac406692b3.png">

The JSON files:
[TC3Q7MAJXF.com.adguard.safari.AdGuard.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5581494/TC3Q7MAJXF.com.adguard.safari.AdGuard.zip)

**Comment by Oleg-Chashko** [comment]
<img width="1022" alt="Bildschirmfoto 2020-11-23 um 08 48 19" src="https://user-images.githubusercontent.com/62497891/99938863-0b570380-2d69-11eb-854a-ee9de05487c7.png">

The JSON files:
[TC3Q7MAJXF.com.adguard.safari.AdGuard.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5581537/TC3Q7MAJXF.com.adguard.safari.AdGuard.zip)

**Comment by Oleg-Chashko** [comment]
@ameshkov 
<img width="1022" alt="Bildschirmfoto 2020-11-23 um 09 08 54" src="https://user-images.githubusercontent.com/62497891/99940017-aa7cfa80-2d6b-11eb-9591-c2ea1e370dde.png">

The JSON files:
[TC3Q7MAJXF.com.adguard.safari.AdGuard.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5581608/TC3Q7MAJXF.com.adguard.safari.AdGuard.zip)

**Comment by ameshkov** [comment]
> Easily achieved with the test: AdGuard for Safari - Pause 15sec

Could you please explain what do you mean by "pause 15 sec"?

**Comment by Oleg-Chashko** [comment]
@ameshkov 
> > Easily achieved with the test: AdGuard for Safari - Pause 15sec
> 
> Could you please explain what do you mean by "pause 15 sec"?

A JavaScript error occurred in the main process #406
<img width="910" alt="Bildschirmfoto 2020-11-23 um 10 25 01" src="https://user-images.githubusercontent.com/62497891/99946281-64796400-2d76-11eb-9e59-9fad1a62467e.png">

_If you want, you can give me the beta version of the application and I will check it for you._

**Comment by Oleg-Chashko** [comment]
@ameshkov
If you fail to check with this test, since I use a certain sequence. I will gladly help. I'll be your beta tester.

**Comment by superlex** [comment]
So it looks like a duplicate :p
https://github.com/AdguardTeam/AdGuardForSafari/issues/418

**Comment by Oleg-Chashko** [comment]
@ameshkov
**No problem, you can close the topic!**
The test took about 20 minutes: AdGuard for Safari - Pause 15sec
The app loads faster, Thank you!

**Comment by superlex** [comment]
It looks like fixed here too, thank you!

**Comment by superlex** [comment]
Please, re-open :(

<img width="769" alt="dgfkj" src="https://user-images.githubusercontent.com/1375223/100487565-9dfcf700-3109-11eb-99f7-eec1a0e6d360.png">

Version 1.8.8 from MAS
macOS Mojave
Safari 14.0.1

**Comment by ameshkov** [comment]
Please export logs

**Comment by ameshkov** [comment]
"Export logs and system info" now includes content blockers info so we'll be able to find out what rule is breaking the content blocker compilation.

Also, a couple more questions (please do export before checking it):
1. Does the issue go away if you check-uncheck any filter?
2. Can you narrow it down to a specific filter?

**Comment by superlex** [comment]
@ameshkov 
Same as https://github.com/AdguardTeam/AdGuardForSafari/issues/456
Same steps with EasyList Italy instead of French filter, same result.

Here my log (before desabling and re-enabling EasyList Italy)

[adg_safari_logs_1606568637520.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5610641/adg_safari_logs_1606568637520.zip)

Thank you!

**Comment by Mizzick** [comment]
Here we have an original compilation error:
[2020-11-28 14:03:20.366] [info] Content-blocker com.adguard.safari.AdGuard.BlockerExtension set result : {"result":"error", "error":{"domain":"WKErrorDomain", "code":2, "descr":"Impossibile completare l'operazione. (WKErrorDomain errore 2.)", "userInfo":"{
    NSHelpAnchor = "Rule list compilation failed: Invalid or unsupported regular expression.";
}"}

**Comment by akmLaVx** [comment]
The error seems to have come back, this time affecting **Base filter**.

Configuration: macOS 11 Big Sur + AdGuard for Safari
Exported logs available in helpdesk ticket 3052960.

**Comment by TheHasagi** [comment]
@akmLaVx 

Ask a customer to update to the latest version of the app, as I can see from the logs there is 1.8.6 and the latest realease version is 1.8.9.

**Comment by ameshkov** [comment]
>  latest realease version is 1.8.9.

It's 1.8.10 already :)
