### ISSUE TITLE
Advanced Blocking extension severely hampers scrolling performance on some sites

### ISSUE THREAD

**Issue by devburke** [AdguardTeam/AdGuardMiniForMac#441]
### Issue Details

* AdGuard for Safari version: 1.8.6
* Environment name and version: Safari 14.0.1 (16610.2.11.51.8)
* Operating System: macOS Big Sur 11.0.1
* Filters you use in AdGuard: Base filter, mobile ads filter, tracking protection filter, social media filter, annoyances filter (all AdGuard), Malicious URL blocklist, Spam404, and NoCoin
* Any other browser extensions you have installed: Dark Mode for Safari, NewsGuard, PiPer, and IINA (not enabled)

* **Version of AdGuard for Safari:**
  * 1.8.6
* **Environment name and version:**
  * Safari 14.0.1 (16610.2.11.51.8)
* **Operating system and version:**
  * macOS Big Sur 11.0.1
* **Filters you use in AdGuard:**
  * Base filter, mobile ads filter, tracking protection filter, social media filter, annoyances filter (all AdGuard), Malicious URL blocklist, Spam404, and NoCoin
* **Any other browser extensions you have installed:**
  * Dark Mode for Safari, NewsGuard, PiPer, and IINA (not enabled)

### Expected Behavior
Scrolling performance will be unaffected by AdGuard.

### Actual Behavior
On certain websites (such as the skill tree on Duolingo.com), scrolling is severely stuttery when Advanced Blocking extension is enabled.

### Screenshots
N/A

### Additional Information
Simply disabling the extension and then reloading the page dramatically improves performance, and vice versa.

**Comment by ameshkov** [comment]
We need to know what sites exactly are affected.

We'll check Duolingo, anything else?

**Comment by devburke** [comment]
I’d noticed scrolling issues on Reddit and Youtube comments as well, but at the time I thought it was just a browser issue. Since I’ve discovered the extension problem, I haven’t been able to verify that the extension is affecting either of those other sites (it was always most extreme on Duolingo, of the sites that I’d seen). So perhaps I mislabeled this issue. It at least exists for Duolingo, and I imagine if it exists there, it may affect other sites as well, but I do not have any others that I can definitely say that it affects.

**Comment by Sam5883** [comment]
scrolling is lagging like hell on [vg](https://www.vg.no/spesial/2020/corona/) as well, if advanced blocking is enabled.

**Comment by devburke** [comment]
FWIW, I just loaded up vg with it enabled and disabled, and either way I get pretty bad scrolling performance there. Could just be the site. Have you noticed improvement when you turn off advanced blocking?

**Comment by devburke** [comment]
Having tested a little more, I’m pretty confident that YouTube comment scrolling is also affected by the extension. It gets much smoother after the extension is disabled.

**Comment by Sam5883** [comment]
> FWIW, I just loaded up vg with it enabled and disabled, and either way I get pretty bad scrolling performance there. Could just be the site. Have you noticed improvement when you turn off advanced blocking?

on my other device (MBP 2015), which has adguard for mac, scrolling is smooth as it should be, so i'm guessing it's related

**Comment by ameshkov** [comment]
Hey everyone, could you please test with the latest beta version?

It has some important changes that may be related:
https://agrd.io/safari_beta

**Comment by devburke** [comment]
Looks all better to me!

**Comment by devburke** [comment]
Is it expected behavior that the beta resets all my settings back to default? The button to refresh filters also doesn't work, it says they were last updated 9/16, and nothing happens when I click on it.

**Comment by ameshkov** [comment]
> Is it expected behavior that the beta resets all my settings back to default?

Yep, sorry for not mentioning this in the first place:(

> The button to refresh filters also doesn't work, it says they were last updated 9/16, and nothing happens when I click on it.

Yeah, known issue, will be fixed today.

**Comment by devburke** [comment]
No worries! Just wanted to make sure it was known.

**Comment by TheHasagi** [comment]
Seems like it's fixed for now. Closed.
