### ISSUE TITLE
You forgot to change the "Белый список" in Russian translation.

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardMiniForMac#444]
<img width="1023" alt="Белый список" src="https://user-images.githubusercontent.com/62497891/100279003-090dc880-2f66-11eb-8526-273b1aa8312c.png">

**Comment by ameshkov** [comment]
Ну в русском мы это менять не будем, никакой негативной коннотации в нем это не несет и менять устоявшуюся терминологию смысла нет.
