### ISSUE TITLE
Update the shield emblem throughout the app.

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardMiniForMac#448]
_Please update the shield emblem throughout the app._

**Old shield emblem:**
<img width="933" alt="Bildschirmfoto 2020-11-25 um 23 55 41" src="https://user-images.githubusercontent.com/62497891/100290252-3153f200-2f7b-11eb-9ba0-f32b1eb557d3.png">

**New shield emblem:**
<img width="301" alt="AppIcon" src="https://user-images.githubusercontent.com/62497891/100290349-66f8db00-2f7b-11eb-9cb6-b6d860660c54.png">

**Comment by superlex** [comment]
I don't know, maybe this is only for the icon, while in the app window it's correct the old one, like in the site:
https://adguard.com/it/welcome.html

**Comment by Oleg-Chashko** [comment]
@superlex 
To match the general theme of macOS Big Sur, only the background needs to be changed.
**Example:**
![EXPORT ME](https://user-images.githubusercontent.com/62497891/100313048-1356b380-2fb4-11eb-90f9-0537cd39f6a1.png)
_And the guys changed the Logo and the Backing. Now for the overall design in this application, the logo design will have to be changed. I would change. To have a logo everywhere alone._

**Comment by ameshkov** [comment]
The logo in the app UI is the standard AdGuard logo, we can't change it every time we change the icon. Also, it shouldn't follow the icon guidelines, these are different entities.
