### ISSUE TITLE
Adguard 1.8.6 does not work on mac OS 10.13.6 (High Sierra)

### ISSUE THREAD

**Issue by mario-grgic** [AdguardTeam/AdGuardMiniForMac#451]
Just updated Adguard for Safari from macOS App Store to version 1.8.6 on macOS 10.13.6, and Adguard no longer works. Filters fail to update and it displays: 4 filters 0 rules 0 advanced rules. 

It also sometimes pops up a dialog with following error message: 
```
Uncaught Exception:
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)
```

It used to work in older version (I think 1.8.5). 

This is on macOS 10.13.6 (17G14042) High Sierra, Safari Version 13.1.2 (13609.3.5.1.5).

**Comment by tvinzz** [comment]
@mario-grgic, thank for your report. It's already fixed. Please try the latest beta https://agrd.io/safari_beta
