### ISSUE TITLE
UI needs fixing in "Block element on page"

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardMiniForMac#452]
AdGuardForSafari v.1.8.8
<img width="667" alt="Bildschirmfoto 2020-11-27 um 16 08 43" src="https://user-images.githubusercontent.com/62497891/100464217-843dbe80-30cd-11eb-987b-ef6790fba7c6.png">
<img width="667" alt="Bildschirmfoto 2020-11-27 um 16 05 48" src="https://user-images.githubusercontent.com/62497891/100464237-8d2e9000-30cd-11eb-9c73-8209a6761635.png">
<img width="667" alt="Bildschirmfoto 2020-11-27 um 16 05 19" src="https://user-images.githubusercontent.com/62497891/100464248-90298080-30cd-11eb-90dd-62babd56ec1f.png">

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/AdguardAssistant #344](https://github.com/AdguardTeam/AdguardAssistant/issues/344) via [**ZenHub**](https://www.zenhub.com/)
