### ISSUE TITLE
github.com downloads are not signed (high sierra)

### ISSUE THREAD

**Issue by mario-grgic** [AdguardTeam/AdGuardMiniForMac#453]
Trying to download AdGuard for Safari from github.com, but macOS High Sierra refuses to run them, even though "Allow apps from anywhere" is enabled in the system settings.

On the other hand, Apple's App Store refuses to update or do fresh install Adguard for Safari version 1.8.8 on High Sierra.

**Comment by ameshkov** [comment]
Weird, we cannot repro this on our test high sierra machine.

Could you please post screenshots that show how this looks like?

**Comment by einsteinbqat** [comment]
High Sierra

Does not matter if I download from Adguard.com or GitHub.com. It is not signed.
 
![Screen Shot 14](https://user-images.githubusercontent.com/48373997/100530178-abbf8480-31bc-11eb-8cc2-eaae3ee3d6e3.png)

**Comment by crgmrgn** [comment]
You can "work-around" this dialog in the normal way (in Applications, right click on Adguard for Safari and select the "open" action in the pop-up menu, OSX will verify the app and then in the dialog that appears take care to click the open option—which isn't the default—from then on the app will be blessed and work fine) whilst waiting for a resolution on High Sierra.

I saw this behaviour thru testing the 1.8.6-1.8.2 reversion, 1.8.8 release recently, but didn't think to log it … hopefully its just a simple build option misconfiguration for High Sierra ...

**Comment by ameshkov** [comment]
Hm, it seems that the issue is not with AdGuard, but with High Sierra.

Check the threads here:
https://discussions.apple.com/thread/252110775
