### ISSUE TITLE
Add Export Logs button in General settings tab

### ISSUE THREAD

**Issue by Mizzick** [AdguardTeam/AdGuardMiniForMac#466]
I suggest to add a new `Export Logs` button next to Import/Export settings as users usually struggle to find it in tray.
<img width="892" alt="Screenshot 2020-12-01 at 23 12 26" src="https://user-images.githubusercontent.com/13855288/100797601-1118ad00-342b-11eb-8d3e-d0c1f55d7f3e.png">

**Comment by BranchS** [comment]
What if this button in addition to exporting logs also created a mail message with said logs addressed to the appropriate email, with any additional debug info needed in the message? @tvinzz

**Comment by Oleg-Chashko** [comment]
@tvinzz 
Have you decided to leave in the context menu, "Export logs and system info ..."?
Maybe it's better to remove it?
<img width="219" alt="103213203-41117e00-490d-11eb-8fb4-7a4524dd805e" src="https://user-images.githubusercontent.com/62497891/103223180-f3edd600-4925-11eb-9bc9-a0a4626ea26b.png">

**Comment by tvinzz** [comment]
@Oleg-Chashko 
https://github.com/AdguardTeam/AdGuardForSafari/issues/495#issuecomment-751705523
