### ISSUE TITLE
Dark UI theme for "Block element on page"

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardMiniForMac#476]
Add a dark theme for "Block Element On Page" to match your macOS theme settings.

<img width="672" alt="Untitled" src="https://user-images.githubusercontent.com/62497891/101168976-91622c80-363c-11eb-920b-98fa42cb0f63.png">

**Comment by anonyme123** [comment]
Would love this as well!

**Comment by Oleg-Chashko** [comment]
@tvinzz 
Please, if you have the opportunity to fix it. Thank you if you can fix this.
UI needs fixing in "Block element on page" #344

**Comment by Oleg-Chashko** [comment]
@tvinzz 
Brother-Namesake please correct. If you have the opportunity.
<img width="667" alt="100464217-843dbe80-30cd-11eb-987b-ef6790fba7c6" src="https://user-images.githubusercontent.com/62497891/101638414-542bdf00-3a2e-11eb-9f83-7c3757705b16.png">
<img width="667" alt="100464237-8d2e9000-30cd-11eb-9c73-8209a6761635" src="https://user-images.githubusercontent.com/62497891/101638669-9fde8880-3a2e-11eb-8d49-47862f632018.png">
<img width="667" alt="100464248-90298080-30cd-11eb-90dd-62babd56ec1f" src="https://user-images.githubusercontent.com/62497891/101638682-a2d97900-3a2e-11eb-88c9-91b4e1f9ec75.png">

**Comment by tvinzz** [comment]
fixed

**Comment by Oleg-Chashko** [comment]
@tvinzz 
Thank you so much!

**Comment by Oleg-Chashko** [comment]
@tvinzz 
Please improve the visibility of the oriol around the button on a dark theme.
<img width="668" alt="Screenshot 2020-12-28 at 15 45 43" src="https://user-images.githubusercontent.com/62497891/103222654-d8ce9680-4924-11eb-8b81-2c3743279154.png">
