### ISSUE TITLE
RE: can not add AdGuard to my taskbar anymore?

### ISSUE THREAD

**Issue by LustyFarmer** [AdguardTeam/AdGuardMiniForMac#489]
I just re-installed the AdGuard on my Mac computer as it was having an issue on Youtube with preventing me from leaving comments- THAT issue has been resolved, but a NEW issue is now present in that I am unable to add the AdGuard to my taskbar like before next to where I type in web-addresses. It shows at the top when it is running, but I can not openly click it on the taskbar (because it won't add to the taskbar) to block ads on sites like Tumblr where the Adblock isn't working fully, because I can not select what parts to block.

![Screen Shot 2020-12-21 at 9 46 04 PM](https://user-images.githubusercontent.com/39177668/102850338-7a5e6100-43d6-11eb-8902-1aaf755c8b6f.png)

**Comment by TheHasagi** [comment]
@LustyFarmer 

You should go to Safari preferences - Extensions and check that AdGuard for Safari Icon is enabled

<details>

![img](https://uploads.adguard.com/myMoonlqx5y.png)

</details>

**Comment by TheHasagi** [comment]
Probably fixed, should be reopened if needed.
