### ISSUE TITLE
Remove old "Export logs and system info ..." AdGuard for Safari v1.9 beta

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardMiniForMac#495]
Remove old "Export logs and system info ..."
In order not to duplicate and clutter the interface.
<img width="219" alt="Screenshot 2020-12-28 at 12 55 33" src="https://user-images.githubusercontent.com/62497891/103213203-41117e00-490d-11eb-8fb4-7a4524dd805e.png">

**Comment by TheHasagi** [comment]
@Oleg-Chashko 

This is a context menu and it's not a duplicate, just an additional option.
