### ISSUE TITLE
Gmail issue

### ISSUE THREAD

**Issue by GiacomoDD** [AdguardTeam/AdGuardMiniForMac#501]
Hi, when AdGuard extension is active I can't open Gmail's emails. The browser shows the inbox page, but when I click on a single mail nothing happens, just the loading note. I deactivate from Preferences AdGuard extension, and then I was able to open emails.

**Comment by TheHasagi** [comment]
@GiacomoDD 

Hello, which version are you using?

**Comment by GiacomoDD** [comment]
macOS Big Sur Version 11.1
Safari Version 14.0.2 (16610.3.7.1.9)
AdGuard for Safari 1.8.10

**Comment by TheHasagi** [comment]
@GiacomoDD 

And what filters do you use? Are they up to date?

**Comment by zzebrum** [comment]
reopen if needed.
