### ISSUE TITLE
AdGuard for Safari ignores $1p modifier from uBlock Origin filters

### ISSUE THREAD

**Issue by shapiro125** [AdguardTeam/AdGuardMiniForMac#508]
I supplement AdGuard for Safari with the uBlock Origin filters. In the [Unbreak filter](https://github.com/uBlockOrigin/uAssets/blob/master/filters/unbreak.txt), there is a rule `@@||myaccounts.capitalone.com^$script,1p` that's required to get the page account login to work.

<img width="1444" alt="Screen Shot 2021-01-07 at 3 33 19 PM" src="https://user-images.githubusercontent.com/7659910/103942121-e262b600-50fd-11eb-9216-0bd187702274.png">

If I add the rule manually in a different format to my user filters – `@@||myaccounts.capitalone.com^$script,~third-party` – the page loads fine.

Thanks!

**Comment by ameshkov** [comment]
@tvinzz we'll need to add `1p`/`3p` support to the converter
