### ISSUE TITLE
Crash - v.1.9.* beta

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardMiniForMac#517]
1. Crash
[adg_safari_logs_1611743982437.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5879730/adg_safari_logs_1611743982437.zip)
[AdGuardForSafariExtension_2021-01-27-090952_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5879734/AdGuardForSafariExtension_2021-01-27-090952_MacBook-Pro.crash.zip)

2. Crash
[adg_safari_logs_1611748103744.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5879939/adg_safari_logs_1611748103744.zip)
[ConverterTool_2021-01-27-123226_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5879914/ConverterTool_2021-01-27-123226_MacBook-Pro.crash.zip)

**Comment by TheHasagi** [comment]
@Oleg-Chashko 

Got the logs thank you. Did it happen once or there are steps to reproduce?

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko
> 
> Got the logs thank you. Did it happen once or there are steps to reproduce?

Did it happen once? Yes.
**2. Crash**
After opening the window: 
<img width="904" alt="Screen Shot 2021-01-28 at 19 52 38" src="https://user-images.githubusercontent.com/62497891/106185065-a40f6280-61a2-11eb-825a-eb1063b7ebdd.png">

**1. Crash**
If you say after viewing the log where to look. I will search as this reproduce. 

P.S.: Version 1.9.0 beta is very stable and lightweight. Thank you. A month without crashes, except for these two.

**Comment by Oleg-Chashko** [comment]
@TheHasagi 
Crash again, I'll try to figure out how to cause it. 
Do you have any hints looking at the log for me. 

**3. Crash**
[adg_safari_logs_1611867560579.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5889979/adg_safari_logs_1611867560579.zip)
[AdGuard for Safari_2021-01-28-212157_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5889983/AdGuard.for.Safari_2021-01-28-212157_MacBook-Pro.crash.zip)

**Comment by Mizzick** [comment]
Number 3 looks like #505, please check the memory usage in this case.

This might be helpful:
https://github.com/AdguardTeam/AdGuardForSafari/issues/505#issuecomment-762449659

**Comment by Oleg-Chashko** [comment]
@Mizzick 
1. I read this topic about two weeks ago and checked the memory leak for about a week. There is no leakage, possibly because we are using different ad filters. 99% this is not my case.
<img width="982" alt="Screen Shot 2021-01-29 at 18 00 36" src="https://user-images.githubusercontent.com/62497891/106305632-35dba600-625d-11eb-9ada-e04e06bd61e9.png">
Question: if it is possible to receive a more extended log? To give it to you.

**Comment by Oleg-Chashko** [comment]
@Mizzick, @TheHasagi 
I read this topic about two weeks ago and checked the memory leak for about a week. There is no leakage, possibly because we are using different ad filters. 99% this is not my case.

Test:
**Launched AdGuard** 
<img width="1009" alt="Screen Shot 61 2" src="https://user-images.githubusercontent.com/62497891/106398715-d7f1be80-6414-11eb-94c6-b2bf326109bd.png">
**One day of AdGuard work without rebooting** 
<img width="965" alt="Screen Shot 326" src="https://user-images.githubusercontent.com/62497891/106398795-2e5efd00-6415-11eb-8497-0fd515c7d681.png">
**Trying to increase the maximum memory consumption of AdGuard**
_Real-time recording without editing._

https://user-images.githubusercontent.com/62497891/106398899-cc52c780-6415-11eb-93f5-2f49565d78ac.mov

**Memory consumption of AdGuard after the test has stabilized at about 300MB** 
_There were no crashes during the test period._

**Comment by Oleg-Chashko** [comment]
AdGuard for Safari v.1.9.3 beta
4. Crash
[adg_safari_logs_1612371236711.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5920124/adg_safari_logs_1612371236711.zip)
[AdvancedBlocking_2021-02-03-171712_MacBook-Pro.crash.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5920128/AdvancedBlocking_2021-02-03-171712_MacBook-Pro.crash.zip)

**Comment by tvinzz** [comment]
I serialised the last crash. The problem caused not by AdGuard. Looks like it's an Apple bug.
Please check the similar thread on Apple Dev forum:
https://developer.apple.com/forums/thread/116649

**Comment by Oleg-Chashko** [comment]
> I serialised the last crash. The problem caused not by AdGuard. Looks like it's an Apple bug.
> Please check the similar thread on Apple Dev forum:
> https://developer.apple.com/forums/thread/116649

Thanks @tvinzz, I understood everything, I closed the topic.
