### ISSUE TITLE
User Rules Behavior Mis-Matches Documentation

### ISSUE THREAD

**Issue by JSPSolvent** [AdguardTeam/AdGuardMiniForMac#520]
### Details

* AdGuard for Safari version: Adguard for Safari 1.8.10
* Environment name and version: Safari 12.1.2
* Operating System: macOS Sierra 10.12.6
* Filters you use in AdGuard: Base/Recommended
* Any other browser extensions you have installed: N/A

### Question:

Hi, I have a question (inquiry) about blocking popups with the `$popup` tag, how can this be implemented in the user filter in 1.8.x onwards versions to mimic its older behavior (pre-1.8.x) to block all popups from a specific domain without blocking the actual domain itself? 

As far as I can see the [AdGuard Documentation](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters) is still referring to `||domain.com^$popup`. However the current behavior of `||domain.com^$popup` is the same as `||domain.com^` (i.e. ignoring the modifier tag). 

Note that `||domain.com^$popup` modifier works as expected in Adguard for Chrome and Adguard for iOS latest versions. 

Is this a bug? Is there a workaround? 
Appreciate it.

**Comment by TheHasagi** [comment]
@tvinzz 

The question remains open.

**Comment by tvinzz** [comment]
@JSPSolvent,

> However the current behavior of ||domain.com^$popup is the same as ||domain.com^ (i.e. ignoring the modifier tag).

Yes, for the moment`$popup` modifier works this way and can't be implemented properly because of Safari restrictions.
Looking forward for a future Safari versions to have more opportunities.
