### ISSUE TITLE
No longer blocking ads

### ISSUE THREAD

**Issue by cab2463** [AdguardTeam/AdGuardMiniForMac#533]
The app does not seem to be working at all. Even after manually blocking an element blocking fails.

**Comment by TheHasagi** [comment]
@cab2463 

Hello, can you describe the issue with more details and steps to reproduce?

**Comment by cab2463** [comment]
I’m not sure what more details to give. The app that I purchased doesn’t do what it is supposed to do. It is literally NOT blocking ads. There is no reason to have it installed because it is not doing what it is supposed to do. No ads ads being blocked - like literally NONE.

Sent from my iPhone

On Feb 10, 2021, at 3:26 AM, Alexander <notifications@github.com> wrote:

﻿

@cab2463<https://github.com/cab2463>

Hello, can you describe the issue with more details and steps to reproduce?

**Comment by TheHasagi** [comment]
@cab2463 

Please tell me if I understand correctly that we are talking about iOS? Have you tried contacting support before?

**Comment by cab2463** [comment]
No, Mac OS

Sent from my iPhone

On Feb 10, 2021, at 8:24 AM, Alexander <notifications@github.com> wrote:

﻿

@cab2463<https://github.com/cab2463>

Please tell me if I understand correctly that we are talking about iOS? Have you tried contacting support before?

**Comment by TheHasagi** [comment]
Issue moved to [AdguardTeam/AdguardForMac #832](https://github.com/AdguardTeam/AdguardForMac/issues/832) via [**ZenHub**](https://www.zenhub.com/)
