### ISSUE TITLE
Pause for Ad Blocking isn't working properly

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdGuardMiniForMac#535]
AdvancedBlocking module continues working while the app is paused. 

### Steps to reproduce:

1. Pause AdGuard
2. Open Settings -> Filters
3. You'll see something like this: `9 filters, 0 rules, 0 advanced rules.`
4. Check filters updates
5. Wait a little bit
6. You'll see `9 filters, 83691 rules, 17161 advanced rules.`
7. All the rules will be applied again (you can add a test rule `example.org#?#body` to check this).

### Expected Behavior

Application work is on pause

### Actual Behavior

Application continues to block

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

AdGuard for Safari 1.9.3 beta

**Comment by Oleg-Chashko** [comment]
@TheHasagi 

It doesn't work quite like that for me, "Pause AdGuard for Safari" works fine for me in pause.
And if you completely unload the "AdGuard for Safari" application, the blocking works, although in theory it shouldn't. 
This is possibly related to the topic I opened 10 days ago: Not a permanent bug with displaying the status of the extension.
https://github.com/AdguardTeam/AdGuardForSafari/issues/531#issue-802956566

- "Pause AdGuard for Safari" works fine for me in pause.


https://user-images.githubusercontent.com/62497891/108231723-569f6900-7142-11eb-8a2a-8d5d9dc0829b.mov

- The blocking works, although in theory it shouldn't.

https://user-images.githubusercontent.com/62497891/108232197-cf062a00-7142-11eb-8103-fa440bf5b1e8.mov

**Comment by ameshkov** [comment]
@TheHasagi this is not what my bug was about.

1. Pause AdGuard
2. Open Settings -> Filters
3. You'll see something like this: `9 filters, 0 rules, 0 advanced rules.`
4. Check filters updates
5. Wait a little bit
6. You'll see `9 filters, 83691 rules, 17161 advanced rules.`
7. All the rules will be applied again (you can add a test rule `example.org#?#body` to check this).
