### ISSUE TITLE
Some rules work incorrectly

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdGuardMiniForMac#537]
### Issue Details

* AdGuard for Safari version: 1.9.3 Beta
* Environment name and version: 14.0.3 (16610.4.3.1.4)
* Operating System: macOS Big Sur 11.2.1 (20D74)

### Steps to reproduce
1. Add this rule:
`||a.a^`
2. Go here -[https://a.allegroimg.com/s180/11d797/046ee76240cbaeaccf98b7c048b5/Powerbank-Anker-PowerCore-Metro-Essential-20000-PD](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://a.allegroimg.com/s180/11d797/046ee76240cbaeaccf98b7c048b5/Powerbank-Anker-PowerCore-Metro-Essential-20000-PD)

### Expected Behavior

Website shouldn't be blocked.
### Actual Behavior

Website is blocked.
### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/108995931-0e31ff00-769e-11eb-97b5-52e39f8d2750.png)

</details>

**Comment by maciejtarmas** [comment]
Same on iOS. Looks like there's some error when converting rules to Safari content blocking syntax.

**Comment by krystian3w** [comment]
ping
