### ISSUE TITLE
Question: only to @ameshkov, @TheHasagi

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardMiniForMac#563]
Question: to @ameshkov, @TheHasagi please answer as the application is protected from the simplest malicious file "adguard-settings-xxxxxxx_xx.json".
The most common little-understanding user imports this file into the application. The load on the processor will increase, the operating time will decrease (Mac Book,..), the time for opening pages in the browser will increase, many sites will not open, the application interface is freezing.
For the ordinary, little-understood user, importing the configuration file (as it is done at the moment) is not safe. But that's just my opinion. I would like to hear from you on this issue. Thank you for understanding.

P.S.: _Most users, ordinary people and have little understanding of software, take this into account when you consider my question._

Made the change quickly, didn't try too hard, just for example.

[adguard-settings-2021325_882.json.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/6202878/adguard-settings-2021325_882.json.zip)

**Comment by ameshkov** [comment]
Well, adding some minimal validation is a good idea, but we won't be able to have a protection against everything. After all, it is always possible to manually change the app settings and break all websites.

**Comment by Oleg-Chashko** [comment]
Password request when importing settings and warning not to use third-party settings. 
Only those that he himself created. And he himself was responsible for his actions if he uses a third party setting. To remove the responsibility from the AdGuard Firm for the lack of competent user actions. Legal protection, not technical protection. We warned and then the user must think about the consequences.

**Comment by Oleg-Chashko** [comment]
@ameshkov
Thanks Andrey for answering. Please delete this topic and if you want to make a request for this function. Describe her as you want. Thanks again for your time.

**Comment by Oleg-Chashko** [comment]
> Well, adding some minimal validation is a good idea, but we won't be able to have a protection against everything.
 **After all, it is always possible to manually change the app settings and break all websites.**

When you import into "User rules" you can see which rules were accepted. When you import into "Allowlist" you can also see which rules were accepted. When you turn on the filters, you can also see what you are doing. But when you import general settings, it’s not visible at all, and it’s not clear whether the rules were accepted or not, and what and where changed, it’s not clear at all, there’s no banner. Something is not finalized here.

**Comment by ameshkov** [comment]
> But when you import general settings, it’s not visible at all, and it’s not clear whether the rules were accepted or not, and what and where changed, it’s not clear at all, there’s no banner. Something is not finalized here.

A dialog window that summarizes the import result?

**Comment by Oleg-Chashko** [comment]
> > But when you import general settings, it’s not visible at all, and it’s not clear whether the rules were accepted or not, and what and where changed, it’s not clear at all, there’s no banner. Something is not finalized here.
> 
> A dialog window that summarizes the import result?

@ameshkov 
- I depicted it quickly, the main thing is to convey the meaning of the idea.
- Why the password: because the Adguard application partially acts as a "firewall". I gave the analogy with a "firewall" because that's the only thing that came to my mind.

1. Window - Import settings
<img width="766" alt="Import settings" src="https://user-images.githubusercontent.com/62497891/112635107-b670ea00-8e3b-11eb-90f6-8ca66938ea56.png">

2. Password
<img width="511" alt="Bildschirmfoto 2021-03-26 um 13 55 01" src="https://user-images.githubusercontent.com/62497891/112635182-c7b9f680-8e3b-11eb-8877-c527f81c2826.png">

3. In the title of the application
<img width="781" alt="Your settings have been accepted" src="https://user-images.githubusercontent.com/62497891/112635219-d30d2200-8e3b-11eb-88b8-fad5c1b4e8a7.png">

**Comment by ameshkov** [comment]
It'd be better to file it as a separate feature request.

One note though - I don't think password is needed here. Settings aren't password-protected, it makes little sense to protect import when anyone can just check whatever options they need.

**Comment by Oleg-Chashko** [comment]
@ameshkov 
You would not be able to submit this request, the more you know better how to make this function better. And I'm at the workplace now, please.
