### ISSUE TITLE
Format tag not replaced by number of filters

### ISSUE THREAD

**Issue by kinoute** [AdguardTeam/AdGuardMiniForMac#566]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version:  1.19.11
* Environment name and version: Version 14.0.3 (14610.4.3.1.7)
* Operating System: macOS Mojave 10.14.6
* Filters you use in AdGuard: plenty
* Any other browser extensions you have installed: None

### Expected Behavior

The number of filters should appear

### Actual Behavior
It seems the format tag for strings is not replaced by the number of filters (see screenshot)

### Screenshots

<details><summary>Screenshot:</summary>

![Capture d’écran 2021-03-31 à 18 17 18](https://user-images.githubusercontent.com/623763/113177390-bf075d00-924d-11eb-8000-90a4a02dca67.png)

</details>

**Comment by Oleg-Chashko** [comment]
Hi @kinoute 
https://github.com/AdguardTeam/AdGuardForSafari/issues/515#issuecomment-787123014
https://github.com/AdguardTeam/AdGuardForSafari/issues/515#issuecomment-787929091
