### ISSUE TITLE
Youtube video playback error

### ISSUE THREAD

**Issue by zambranolp** [AdguardTeam/AdGuardMiniForMac#589]
Hi! 

Ads seems to vanished as soon as i installed the extension for Safari but now i cannot play any video on youtube :( 

![Screen Shot 2021-05-07 at 17 44 45](https://user-images.githubusercontent.com/45477198/117475130-fd362180-af5b-11eb-97d3-ef22ba6d5d21.png)

Thanks! 

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by zzebrum** [comment]
@zambranolp what filters are enabled in AdGuard for Safari?

**Comment by Ant-V** [comment]
@zambranolp Had the same issue, updated the filters, now video works, but so do ads...
An sort of a solution: hit share, embed and play video from there. No ads there, although the viewing experience is definitely worse...

**Comment by zambranolp** [comment]
> @zambranolp what filters are enabled in AdGuard for Safari?

All filters enabled. 

> @zambranolp Had the same issue, updated the filters, now video works, but so do ads...
> An sort of a solution: hit share, embed and play video from there. No ads there, although the viewing experience is definitely worse...

I just did the same, manually updated the filters (I thought they were automatically updated when installed but apparently not) and then restarted everything (Safari, AdGuard, etc...), it is now playing videos with no adds so far. 

I'll update if something different happens. Thanks!

**Comment by Oleg-Chashko** [comment]
@zambranolp 
_(I thought they were automatically updated when installed but apparently not)_
Filters don't update automatically #586

**Comment by zzebrum** [comment]
@zambranolp we've made some changes in filters today, please update filters manually and check.

**Comment by crgmrgn** [comment]
Todays changes seem to have crippled the blocking of ads on YT, also seems to trigger significant CPU usage peaks, whereas previously smooth playback was observed (on macOS 10.13.6, Safari 13.1.2, AfS 1.9.13).

**Comment by ameshkov** [comment]
@crgmrgn I really doubt that's on us, YT made some changes on their side.

What's important is that if you have "Advanced Blocking" extension disabled, YT ad blocking will be not ideal. We've found a way to block ad videos, but there'll be a noticeable delay before the video starts playing.

**Comment by TheHasagi** [comment]
@zambranolp Any updates?

**Comment by zambranolp** [comment]
> @zambranolp Any updates?

Hi! I've been testing AdGuard with Youtube (a lot...) these days and haven't found any other issues. The video starts after 1 or 2 seconds without ads, any problem on my side. Filters just updated automatically today May 20th at 19h03 GMT+01, looks like updating the filters manually solved my issue.
