### ISSUE TITLE
Updating Filter Selections does not work

### ISSUE THREAD

**Issue by ekmixon** [AdguardTeam/AdGuardMiniForMac#601]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: Version 1.9.13
* Environment name and version: Safari Version 14.1 (15611.1.21.161.7, 15611)
* Operating System: macOS Catalina Version 10.15.7 (19H1030)
* Filters you use in AdGuard: Allowlist, Ad Blocking, Privacy, Social Widgets, Annoyances, Security
* Any other browser extensions you have installed: Pocket

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Expected Behavior
Whenever I select a filter it should remain selected.  I should go into the Preferences select the filters I want, and when I go back in after closing out the window what I selected previously should still be selected.

### Actual Behavior
Under the Annoyances filter Grouping, I select Web Annoyances Ultralist, Adblock Warning Removal List, I don't care about cookies.  The next time I go back into the Annoyances filter list after closing out the Preferences page and reopening it all of the filters I selected are turned off except for the AdGuard Annoyances Filter.  This happens with the Security Filter as well.  The changes I make to the various filters do not remain. 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by TheHasagi** [comment]
@ekmixon 

Please, collect the log files with the reproduced issue by clicking on AdGuard for Safari icon - Export logs and system info and send them to devteam@adguard.com with the subject `issue/601`.

**Comment by TheHasagi** [comment]
@ekmixon 

Did not received any info from you. Please, collect the logs and system information as described in the comment above and send it to devteam@adguard.com with the subject `issue/601`.

**Comment by TheHasagi** [comment]
@ekmixon 

Did not received the logs from you. Please, follow the instruction above.

**Comment by TheHasagi** [comment]
Closed due to no response. Should be reopened if needed.
