### ISSUE TITLE
The information displayed in "Content blockers"

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdGuardMiniForMac#604]
Problem with the information displayed in "Content blockers"
Please explain to me why the number 26 is everywhere and how it mathematically counts.
And what everywhere, the words "User rules" and "Allowlist"?
Unfortunately, at this point, the "Content blockers" section is more confusing to me than helpful.

- Content blockers:
<img width="1072" alt="119554150-a2def280-bd9c-11eb-8e03-1ab03cde9b55" src="https://user-images.githubusercontent.com/62497891/119658138-1597ae80-be2d-11eb-9537-57d40a1287e3.png">

- Filters:
<img width="1072" alt="Filters" src="https://user-images.githubusercontent.com/62497891/119554232-bdb16700-bd9c-11eb-8208-99389405b132.png">

**Comment by TheHasagi** [comment]
@Oleg-Chashko 

It's all about your user rules and allowlist that operates by all content blockers that's why you see 26 and `User rules & Allowlist`. Maybe in future updates, we will re-design this page so it can be more informative.

**Comment by Oleg-Chashko** [comment]
@TheHasagi 
Got it, thanks for the answer. It is desirable that this section, was more understandable to the user.

**Comment by zzebrum** [comment]
@Oleg-Chashko the problem with safari is that each content blocker is independent. It means all rules from one content blocker can't affect rules from the other content blocker. If you want to negate some rule from a third-party filter or use for example $badfilter modifier, it can be done only if the user rule you are creating will be placed in the exact content blocker where the rule you need to affect is present. That's why User rules and Allowlist rules need to be in each content blocker and it is quick and easy way to check if they are compiled without any error for us and our users.

**Comment by Oleg-Chashko** [comment]
@zzebrum 
Thank you for answering.
I understand. What about the math, please explain.
23(User rules)+6(Allowlist)=29, these are my calculations.
23(User rules)+6(Allowlist)=26, this application.
Please explain the mathematics of the application.

P.S.:
I did the test left 3User rules: 3(User rules)+6(Allowlist)=9
And the app has counted correctly!
This is math, not quantum mechanics.

<img width="1005" alt="Screen Shot 2021-06-01 at 12 18 01" src="https://user-images.githubusercontent.com/62497891/120307776-a9f18d80-c2d3-11eb-95b6-8a5757534e8e.png">
<img width="1019" alt="Screen Shot 2021-06-01 at 12 18 40" src="https://user-images.githubusercontent.com/62497891/120307792-ae1dab00-c2d3-11eb-9f2e-ce4761dd6e96.png">

**Comment by zzebrum** [comment]
@Oleg-Chashko some rules were not converted probably

**Comment by zzebrum** [comment]
Though there are some problems with the math on a Filters page which we need to fix.

**Comment by Oleg-Chashko** [comment]
@zzebrum 
I figured out where the problem is, the problem is not with the math! It's an error with the description of what we're counting. And we don't count (Rules), we count (Domains). In the description is the word (Rules). It should be (Domains). Do you open, this Issue, or should I open a new Issue?
<img width="445" alt="Screen Shot 2021-06-01 at 16 17 41" src="https://user-images.githubusercontent.com/62497891/120340672-8a1f9100-c2f6-11eb-8d27-9863fb5cb956.png">

**Comment by zzebrum** [comment]
@Oleg-Chashko overall it is 'rules', not 'domains'. But I see what you mean here. Let me check with new rules converter 👌

**Comment by Oleg-Chashko** [comment]
@zzebrum 
> overall it is 'rules', not 'domains'. 

1. I'm not sure that's true. Because the original source is a mixture of 'rules' and 'domains'. 
Only the creator, with can on, this answer.
Example Filters : 
<img width="144" alt="Screen Shot 2021-06-01 at 16 39 45" src="https://user-images.githubusercontent.com/62497891/120343581-2054b680-c2f9-11eb-845d-1a9855296708.png">

> But I see what you mean here. Let me check with new rules converter 👌
or this is how converter works. anyway, I'll take a look into it.

Thank you for responding. I look forward to hearing from you in the future. Thank you.

**Comment by zzebrum** [comment]
@Oleg-Chashko I guess my assumption that the number on filters tab and the number on Content blockers page must be even is wrong. 

On the Filters tab the counter shows total amount of rules before converting and  on Content blockers page - after.

**Comment by Oleg-Chashko** [comment]
@zzebrum 
Now, I get it, in short, (Content blockers) is a technical page for you, not for the user. Then why, the technical page, to the average user on the first page? And the button "Enable hardware acceleration"? Even in the Chrome browser, this button "Enable hardware acceleration" is not on the first page? 
Thank you for clarifying the conversion, the issue is completely closed with "Content blockers".
I'm sorry to bother you, I just want to get to the bottom of this.
<img width="961" alt="Screen Shot 2021-06-01 at 17 36 22" src="https://user-images.githubusercontent.com/62497891/120353954-5c404980-c302-11eb-9b61-bb28b2609104.png">

**Comment by zzebrum** [comment]
@Oleg-Chashko well, maybe that is a good idea to move some options to Advanced settings in the future.

**Comment by Oleg-Chashko** [comment]
@zzebrum 
> @Oleg-Chashko well, maybe that is a good idea to move some options to Advanced settings in the future.

Thank you very much for your communication, I am very pleased. I hope in the future, you will not forget about it and remember, and change the interface of the application a little bit.
