### ISSUE TITLE
Adguard for Safari using significant energy

### ISSUE THREAD

**Issue by n0rt0nthec4t** [AdguardTeam/AdGuardMiniForMac#620]
Latest update to Adguard safari supporting M1 based systems (1.9.18), macOS 11.4 now reports Adguard for Safari using significant energy when rule processing its enabled. Pausing Adguard, it is not longer reported. This occurs even if Safari being idle and/or minimised

<img width="335" alt="Screen Shot 2021-06-09 at 9 48 56 am" src="https://user-images.githubusercontent.com/19759130/121283024-cddd5080-c91d-11eb-931f-c815c93dbecc.png">

**Comment by BrushXue** [comment]
Could you please check if your Adguard is running in native or rosetta?
I feel this is somehow related to my issue https://github.com/AdguardTeam/AdGuardForSafari/issues/621
Here's my energy usage in M1 Mac mini
![Screen Shot 2021-06-09 at 12 03 01 AM](https://user-images.githubusercontent.com/12702149/121291345-237e1280-c8b6-11eb-8f8f-e2053e102697.png)

**Comment by n0rt0nthec4t** [comment]
Interesting.. The update push to fix the preferences pane issue is no longer a universal binary...
<img width="856" alt="Screen Shot 2021-06-09 at 2 06 39 pm" src="https://user-images.githubusercontent.com/19759130/121291724-1d2a7d80-c92c-11eb-8c40-870eabe35515.png">
<img width="253" alt="Screen Shot 2021-06-09 at 2 07 52 pm" src="https://user-images.githubusercontent.com/19759130/121291732-1ef44100-c92c-11eb-8f9a-a4e50e759a79.png">

**Comment by ameshkov** [comment]
The hotfix is basically version .13 with an incremented build number, see https://github.com/AdguardTeam/AdGuardForSafari/issues/619#issuecomment-857216691

Regarding the high cpu usage, I've replied in that thread as well, this is not a new thing.

Please reopen this issue if there's a constant high usage. If it only happens on filters reload, this is expected.

Also, you could try the standalone build to see if the native version works better.
