### ISSUE TITLE
Why not support M1

### ISSUE THREAD

**Issue by LongCX** [AdguardTeam/AdGuardMiniForMac#622]
I use Adguard For Safari version 1.9.18 (Include support M1 chip)
But i see in task manager still Intel, not M1 of Apple
<img width="2038" alt="Ảnh chụp Màn hình 2021-06-10 lúc 18 38 07" src="https://user-images.githubusercontent.com/38092914/121518914-3b22db80-ca1b-11eb-8138-26c236af7b75.png">
Anyone can explain me

**Comment by sweetppro** [comment]
strange,
im running v1.9.17 and its running native

**Comment by Dararii** [comment]
> I use Adguard For Safari version 1.9.18 (Include support M1 chip)
> But i see in task manager still Intel, not M1 of Apple
> <img alt="Ảnh chụp Màn hình 2021-06-10 lúc 18 38 07" width="2000" src="https://user-images.githubusercontent.com/38092914/121518914-3b22db80-ca1b-11eb-8138-26c236af7b75.png">
> Anyone can explain me

I have the same issue. Does anyone have a good reason for this?

**Comment by TheHasagi** [comment]
This case can be explained [here](https://github.com/AdguardTeam/AdGuardForSafari/issues/619#issuecomment-856965861). Please, stand by for the updates.
