### ISSUE TITLE
AdguardForSafari for iOS

### ISSUE THREAD

**Issue by iMonZ** [AdguardTeam/AdGuardMiniForMac#628]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

The AdGuard app is pretty limited since it's only a content blocker

### Proposed Solution

Apple adds the whole WebExtension API from Safari on macOS to the iOS devices.
So it's time to support it for iOS too!

### Additional Information

https://developer.apple.com/safari/extensions/

### Checklist

- [ ] replacing the electron app with example SwiftUI for macOS and iOS (iPadOS) because electron is not supported on iDevices
- [ ] Migrating from App Extension to Web Extension (which has a much greater future since Apple maybe drop App Extension support in later updates)

The best way would be dropping the whole AdGuardForSafari and AdGuardForiOS project and just focus on [AdGuardBrowserExtension](https://github.com/AdguardTeam/AdguardBrowserExtension) and add macOS Safari and iDevice Safari support to it.

**Comment by ameshkov** [comment]
Here's our plan:

1. Advanced Blocking extension and Safari Toolbar icon will be transformed into a web extension
2. The same web extension will be used in AdGuard for iOS
3. Eventually, AdGuard for iOS will replace the current AdGuard for Safari.

> and just focus on AdGuardBrowserExtension and add macOS Safari and iDevice Safari support to it.

Safari Content Blocking is not going away and compared to WebExtensions it provides more features. Also, Safari supports only a subset of APIs, for instance, webRequest is completely missing. I doubt it will ever be on par with Chromium/FF so having single code base for all browsers is not an option.

**Comment by iMonZ** [comment]
> Here's our plan:
> 
> 1. Advanced Blocking extension and Safari Toolbar icon will be transformed into a web extension
> 2. The same web extension will be used in AdGuard for iOS
> 3. Eventually, AdGuard for iOS will replace the current AdGuard for Safari. To be precise, it won't fully replace it, but they'll share a lot of code.
> 
> > and just focus on AdGuardBrowserExtension and add macOS Safari and iDevice Safari support to it.
> 
> Safari Content Blocking is not going away and compared to WebExtensions it provides more features. Also, Safari supports only a subset of APIs, for instance, webRequest is completely missing. I doubt it will ever be on par with Chromium/FF so having single code base for all browsers is not an option.

Great!
Will there be a Beta? I would like to try it out!

**Comment by ameshkov** [comment]
At some point, there will be one, but we're rather far from that as this requires rewriting AdGuard for iOS UI part, we'll need to use SwiftUI there which is a new cross-platform framework by Apple.

Short-term, we're working on the web extension part that will replace Advanced Blocking (and will also add that functionality to AdGuard for iOS).

**Comment by iMonZ** [comment]
> At some point, there will be one, but we're rather far from that as this requires rewriting AdGuard for iOS UI part, we'll need to use SwiftUI there which is a new cross-platform framework by Apple.
> 
> Short-term, we're working on the web extension part that will replace Advanced Blocking (and will also add that functionality to AdGuard for iOS).

Sounds great! I would recommend to look into SwiftUI 3 which comes this fall this should have more features (the beta is already out)

**Comment by gedw99** [comment]
Is there a branch where this work is ongoing ? Would like to help

**Comment by iMonZ** [comment]
> Is there a branch where this work is ongoing ? Would like to help, as have this extension for iOS mobiles is awesone

Me too! I can beta test things also

**Comment by ameshkov** [comment]
We'll announce it once the first beta is ready, it will take a couple of weeks probably.

**Comment by iMonZ** [comment]
> We'll announce it once the first beta is ready, it will take a couple of weeks probably.

I’m also open to test the alphas with my iOS 15 device!

**Comment by gedw99** [comment]
@ameshkov thanks for letting us know !

will be cool to have this working

**Comment by gedw99** [comment]
@iMonZ is your is stable as a daily drive ? Would like to test but only have one iOS device that I need to work with Xcode etc ? Did you have to upgrade Xcode ?

**Comment by iMonZ** [comment]
> @iMonZ is your is stable as a daily drive ? Would like to test but only have one iOS device that I need to work with Xcode etc ? Did you have to upgrade Xcode ?

Yes
Of course you have. It’s a new API so you have to upgrade Xcode too

**Comment by gedw99** [comment]
@iMonZ thanks for letting me know. Will try it out

**Comment by JesseFarebro** [comment]
> Safari Content Blocking is not going away and compared to WebExtensions it provides more features. Also, Safari supports only a subset of APIs, for instance, webRequest is completely missing. I doubt it will ever be on par with Chromium/FF so having single code base for all browsers is not an option.

I don't understand this. With Safari 15 they now support __most__ of `declarativeNetRequest` as defined in Manifest v3. As far as WebExtensions are concerned it seems that Safari Content Blocking is going away in favor of `declarativeNetRequest` even though it might not be all there in v15. The [Manifest v3 example](https://github.com/AdguardTeam/tsurlfilter/blob/master/examples/manifest-v3) would have some features missing but it seems likely you could build everything on a single codebase.

**Comment by ameshkov** [comment]
@JesseFarebro declarativeNetRequest misses cosmetic filtering rules completely so it's not a feasible replacement for Safari Content Blocking. We could do the same as in Chromium/FF and do cosmetic filtering via a content script, but it would require people to grant AG more permissions by default while now it's only required for using advanced blocking techniques like scriptlets and extended CSS rules.

Also, I've asked WebKit devs specifically about Safari Content Blocking and they're going to continue supporting it: https://twitter.com/ay_meshkov/status/1401987730373058562

**Comment by JesseFarebro** [comment]
Ahh, interesting, thanks for the response. Correct me if I'm wrong, doesn't the `declarativeNetRequest` API provide a more powerful way of specifying static rules, or are the two APIs fairly equivalent when it comes to features?

**Comment by ameshkov** [comment]
Not in the case of Safari, it supports only a limited subset. Generally, `declarativeNetRequest` as it's planned for Chromium's Manifest V3 provides more options. The tradeoff is that it's almost "static" (most of the rules are pre-compiled into the extension and can't be changed dynamically).

**Comment by floam** [comment]
Safari 18 ain’t looking so bad though.
