### ISSUE TITLE
1.9.19 - crash on Mac OS High Sierra 10.13.6

### ISSUE THREAD

**Issue by phantasm** [AdguardTeam/AdGuardMiniForMac#629]
After updating to 1.9.19, AdGuard for Safari crashes immediately upon launch. Using MBP 17" late 2011 (MacBookPro8,3)

### Issue Details

* AdGuard for Safari version: 1.9.19
* Environment name and version: Safari 13.1.2 (13609.3.5.1.5)
* Operating System: macOS High Sierra 10.13.6
* Filters you use in AdGuard: All defaults
* Any other browser extensions you have installed: None

============= LOG DETAILS ===============

Process:               AdGuard for Safari [3117]
Path:                  /Applications/AdGuard for Safari.app/Contents/MacOS/AdGuard for Safari
Identifier:            com.adguard.safari.AdGuard
Version:               1.9.19 (162)
App Item ID:           1440147259
App External ID:       842621910
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           AdGuard for Safari [3117]
User ID:               501

Date/Time:             2021-06-28 16:55:15.811 +0300
OS Version:            Mac OS X 10.13.6 (17G14042)
Report Version:        12
Anonymous UUID:        155607D8-FAE2-0D2F-D436-DFF7B8E43B14

Sleep/Wake UUID:       849B8B8D-CD5A-406C-8091-BA277B1B1DFF

Time Awake Since Boot: 1500000 seconds
Time Since Wake:       570000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/AdGuard for Safari.app/Contents/MacOS/AdGuard for Safari
  Reason: no suitable image found.  Did find:
	/Applications/AdGuard for Safari.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: code signature invalid for '/Applications/AdGuard for Safari.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework'

	/Applications/AdGuard for Safari.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x104d71000 -        0x104d9cffb +com.adguard.safari.AdGuard (1.9.19 - 162) <047F0054-3415-38F0-AA2D-E21075DC9A82> /Applications/AdGuard for Safari.app/Contents/MacOS/AdGuard for Safari
       0x1137e0000 -        0x11382aadf  dyld (551.5) <CB9BFB56-4511-36F1-A546-891FF770C01C> /usr/lib/dyld

Model: MacBookPro8,3, BootROM 87.0.0.0.0, 4 processors, Intel Core i7, 2,4 GHz, 16 GB, SMC 1.70f6
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In
Graphics: AMD Radeon HD 6770M, AMD Radeon HD 6770M, PCIe
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x859B, 0x43543130323436344246313630422E433136
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x859B, 0x43543130323436344246313630422E433136
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xD6), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 6.0.7f22, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: PLEXTOR PX-128M5Pro, 128,04 GB
Serial ATA Device: MATSHITADVD-R   UJ-8A8
USB Device: USB 2.0 Bus
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Apple Internal Keyboard / Trackpad
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: IR Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.1

**Comment by ameshkov** [comment]
Is this a version from Mac App Store?

Could you please try a standalone version just in case?

**Comment by phantasm** [comment]
> Is this a version from Mac App Store?
yes

> Could you please try a standalone version just in case?
standalone version seems to work fine, thanks.

**Comment by ameshkov** [comment]
I wonder if this is a MAS issue again, we've seen something like that before when they were signing apps incorrectly for macOS Sierra.

**Comment by zzebrum** [comment]
@phantasm does crash happen every time upon starting the app?

**Comment by phantasm** [comment]
> @phantasm does crash happen every time upon starting the app?
I've installed 1.9.19 manually from github releases section, and everything is ok since then.

**Comment by vozersky** [comment]
@phantasm any chance you could try v1.10.4 from MAS and tell us if it's ok?

**Comment by phantasm** [comment]
@vozersky seems to work now

**Comment by vozersky** [comment]
@phantasm thanks!
