### ISSUE TITLE
Allowlists reset and do not stop Adguard function on site.

### ISSUE THREAD

**Issue by mykagr** [AdguardTeam/AdGuardMiniForMac#635]
### Prerequisites

I am running the latest version
I checked the documentation and found no answer
I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.9.19
* Environment name and version: Version 14.1.1 (16611.2.7.1.4)
* Operating System: Mac OS Big Sur 11.4
* Filters you use in AdGuard:
* Any other browser extensions you have installed: Cold Turkey Blocker

### Expected Behaviour
I expected the checkbox for the "Enabled on website" option on the Safari extension dropdown preview to be empty and the site to reload. I expected another entry in the allowlist along with other sites I manually inputted.

### Actual Behaviour
The checkbox was empty for a split second but was filled again and the site did reload. The allowlist was reset and any previous entries were emptied, with only the current site as an entry and even on the current site, Adguard was still functioning.

**Comment by anastenko** [comment]
@mykagr Hello.
We couldn't reproduce it on our end. But we're releasing a new beta soon, so you might want to test the issue's behavior on it.

**Comment by Birbber** [comment]
@mykagr Any news?

**Comment by mykagr** [comment]
I believe it’s been working since the last update supporting Apple Silicon, or the one after that. No issues of the kind since.

Thanks!

With regards,
Mayank Agrawal
