### ISSUE TITLE
I can't prevent popups even if its blocked

### ISSUE THREAD

**Issue by Zaid0507** [AdguardTeam/AdGuardMiniForMac#648]
- [ ✅] I am running the latest version
- [ ✅] I checked the documentation and found no answer
- [ ✅] I checked to make sure that this issue has not already been filed

### Issue Details

when I open a site a get these disturbing popups. It's already blocked but I have to close them one by one and it's really annoying.
* AdGuard for Safari version: Version 1.10.4
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard: none
* Any other browser extensions you have installed: none

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  *  
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  *  none
* **Any other browser extensions you have installed:**
  *  none

### Expected Behavior

I expect not to see the popups 
### Actual Behavior

popups everywhere
### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Birbber** [comment]
@Zaid0507 Hello!
Have you blocked it via "Block an element" feature? Clearing cookies for a site might help.
You've mentioned that you don't use any AdGuard filters: could you try AdGuard Annoyances filter?
Please give us the example of such webpage so we could reproduce it.

**Comment by Birbber** [comment]
@Zaid0507 Any news?

**Comment by Birbber** [comment]
I'm closing this issue due to no response. Please reopen it if the issue occurs.
