### ISSUE TITLE
Adguard for Safari 1.10.4 quits repeatedly

### ISSUE THREAD

**Issue by avincent98144** [AdguardTeam/AdGuardMiniForMac#664]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version YES
- [x] I checked the documentation and found no answer NO
- [x] I checked to make sure that this issue has not already been filed YES

### Issue Details

Although this version has been running smoothly in STP, as of yesterday [and STP update 135] Adguard just quits and only a reboot will enable it again -- for an hour or so, then quits on its ow. Several reboots, same thing. A work around is to fire up the app via TERMINAL in CONTENTS and leave TERMINAL open. So far, the app not quite after 18 hours.

Seems that what changes happened in STP 135, is causing this.

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Birbber** [comment]
@avincent98144 Hello! Sorry for the late reply. We couldn't reproduce the issue on our end.
What OS do you use?
Could you send us the debug logs? Here's what we need you to do:
- Make sure all Safari content blockers are enabled;
- Reproduce the issue and remember the exact time when it happened;
- Open the extension settings --> Export logs and system info;
- Send the archive to apple@adguard.com and mention this issue number in the subject.

**Comment by Birbber** [comment]
@avincent98144 Any news? Have you already sent the debug logs?

**Comment by Birbber** [comment]
Closing this issue due to no response. Please re-open if needed.

**Comment by avincent98144** [comment]
What???

This is the first time I have received  a reply and I already did send the files you requested two days ago.

I also sent a video of the issue.

Please advise!

**Comment by Birbber** [comment]
@avincent98144 Looks like we haven't received it. Please re-send the logs and mention this issue's number.

**Comment by Birbber** [comment]
@avincent98144 Is this issue still reproducible?

**Comment by Birbber** [comment]
@avincent98144 The issue wasn't reproduced on our end. Is it still reproducible?

**Comment by avincent98144** [comment]
It has been doing this intermittently for over 2 months now. 

I have to reboot, sometimes 3 or 4 times and then it will work properly.

**Comment by Birbber** [comment]
@avincent98144 Our team is already working on the issue. Could you share the debug logs?
Here's how to do it:

- Make sure all Safari content blockers are enabled;
- Try to reproduce the issue and remember the exact time when it happened;
-  Open the extension settings --> Export logs and system info;
-  Send the archive to apple@adguard.com and mention this issue number in the subject (You can send the logs as a new email or share a link to the logs destination).

**Comment by avincent98144** [comment]
Anna, the issue occurred with this latest reboot after updating to 12.2.

The email was just sent as you directed.

Anthony

**Comment by Birbber** [comment]
Thanks, will transfer to our devs.

**Comment by avincent98144** [comment]
February 10, 2022 at 10:21:16 AM PST Follow Up #1
