### ISSUE TITLE
Inverted allow list does not work.

### ISSUE THREAD

**Issue by henrymelt** [AdguardTeam/AdGuardMiniForMac#667]
Inverted allow list does not work.

**Comment by Birbber** [comment]
@henrymelt Sorry for the late reply! As we can see it works as expected. Have you tried re-installing AdGuard for Safari?

**Comment by Birbber** [comment]
@henrymelt Any news?

**Comment by Birbber** [comment]
I'm closing this issue due to no response. Please re-open if needed.
