### ISSUE TITLE
Custom filters from prior installation is in effect but is not shown on the UI

### ISSUE THREAD

**Issue by mohsen1** [AdguardTeam/AdGuardMiniForMac#682]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.10.4
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8)) Version 15.2 (17612.3.6.1.6)
* Operating System: (e.g macOS High Sierra 10.13.6) 12.1
* Filters you use in AdGuard: None
* Any other browser extensions you have installed: No

I used to have filters for `instagram.com` and went to change the filter but noticed the UI is telling me there is no custom filters. When I try to add a custom filter for instagram I'm getting an exception 

### Expected Behavior
Show my filters 

### Actual Behavior
No filters 

### Screenshots

<details><summary>Screenshot:

</summary>
<img width="1072" alt="Screen Shot 2022-02-01 at 10 49 56 AM" src="https://user-images.githubusercontent.com/543633/151980814-f773907e-67d4-47f4-813a-f97f673b96bc.png">
<img width="1072" alt="Screen Shot 2022-02-01 at 10 49 45 AM" src="https://user-images.githubusercontent.com/543633/151980836-87ee8904-56ff-4791-8938-757607df462d.png">
<img width="1072" alt="Screen Shot 2022-02-01 at 10 49 14 AM" src="https://user-images.githubusercontent.com/543633/151980841-8cbbb757-cfa7-4e11-a736-63e1a6888f79.png">

</details>

### Additional Information

My filter removes entire Instagram homepage. Disabling extensions in Safari brings it back, it is definitely this extension that is faulty

**Comment by mohsen1** [comment]
I'm not sure how but this issue is resolved itself. I did disable extensions in Safari and enable them again. I also toggled the custom rules on and off a few times.

**Comment by Birbber** [comment]
@mohsen1 Thanks for your report! I will close this issue then. Please re-open if the issue occurs again.

**Comment by mohsen1** [comment]
This is still an issue. Can you point me to exact location of the file for custom filters on Mac? I am going to try to delete it to see if the issue goes away

**Comment by Birbber** [comment]
@mohsen1 Please share your filter, so we could check it. Also send us the debug logs of the application.
Here's how you can do it:
- Make sure all Safari content blockers are enabled;
- Reproduce the issue and remember the exact time when it happened;
- Open the extension settings --> Export logs and system info;
- Send the archive to apple@adguard.com and mention this issue number in the subject as well as the time of reproduction.

That would help us to understand the problem.

**Comment by mohsen1** [comment]
This is my logs. I see the custom filters there in the JSON object but it is not rendered by the extension 


<details>

```
{
    "protocol-version": "1.0",
    "general-settings": {
        "app-language": "en-US",
        "allow-acceptable-ads": true,
        "show-app-updated-disabled": false,
        "update-filters-period": 48,
        "show-tray-icon": true,
        "launch-at-login": true,
        "verbose-logging": true,
        "hardware-acceleration-disabled": false
    },
    "filters": {
        "enabled-groups": [
            1,
            2,
            3,
            4,
            6,
            7,
            0
        ],
        "enabled-filters": [
            10,
            14,
            2,
            3,
            4
        ],
        "custom-filters": [],
        "user-filter": {
            "enabled": true,
            "rules": "slickdeals.net###featDealsAndCoupons\nslickdeals.net###personalizedWidget\nbbc.com###main-wrapper > header:first-child > div.css-n7zdg2.e1nbsi9l0:first-child > div.css-1rdrqig.e1o5up6o5\nft.com##div.n-layout:nth-child(2) > div.n-layout__row.n-layout__row--header:nth-child(5) > div.n-layout__header-before:first-child > div.n-messaging-slot:first-child > div.o-cookie-message.o-cookie-message--alternative.o-cookie-message--active > div.o-cookie-message__outer > div.o-cookie-message__inner\nft.com##div.n-layout:nth-child(2) > div.n-layout__row.n-layout__row--header:nth-child(5) > div.n-layout__header-before:first-child > div.n-messaging-slot:nth-child(2) > div.o-cookie-message.o-cookie-message--alternative.o-cookie-message--active\nslickdeals.net###stickyRightRailWrapper > div:nth-child(2)\nslickdeals.net###stickyRightRailWrapper > div.sideGridBox.featCouponsDiscounts:nth-child(5)\nreuters.com###TxpWgQOM\nfacebook.com##div[data-pagelet=\"RightRail\"]\nfacebook.com##div[aria-label=\"Stories\"]\nfacebook.com##div[role=\"main\"]\nmobile.twitter.com##div[aria-label=\"Timeline: Your Home Timeline\"]\ninstagram.com##main[role=\"main\"]\ntheguardian.com###sp_message_container_414202\ntheguardian.com###article > div.content__main.tonal__main.tonal__main--tone-news:last-child > div.gs-container > div.content__main-column.content__main-column--article.js-content-main-column:first-child > div.content__article-body.from-content-api.js-article__body:last-child > div:nth-child(21)\ntheguardian.com###bannerandheader > header.new-header.pillar-scheme--News:last-child > nav.new-header__inner.gs-container:first-child > div.new-header__cta-bar.hide-until-mobile:nth-child(3)\ntheguardian.com###article > div.content__main.tonal__main.tonal__main--tone-news:last-child > div.gs-container > div.content__secondary-column.js-secondary-column:last-child > div.aside-slot-container.js-aside-slot-container:first-child\neconomist.com###_evidon-banner\neconomist.com###_evidon-background\nmacrumors.com###featured_slider\nhbr.org###main > div.component:nth-child(3) > persistent-banner > section.persistent-banner.hide-for-print\ntheguardian.com###bottom-banner > div.css-kqhjea > div.css-1uiaxdu > div.css-1xgdlo7-container-Container:last-child > div.css-34t5a0:last-child > div.css-1ufa27k-columns-Columns\ntheguardian.com###slot-body-end > div.css-138pfvh > section.css-f9il16\ntheguardian.com###reader-revenue-links-header > div.css-1yfvmzu > div.css-l6t30p:first-child > div.css-1p35o95:first-child\ntheguardian.com###reader-revenue-links-header > div.css-1yfvmzu > div.css-l6t30p:first-child\ntheguardian.com###reader-revenue-links-footer > div.css-1ilyui9 > div\nberdonllp.com###header > a.lets-connect:first-child\nsfgate.com###exp_b0d52c5c-8ef9-44e0-90ab-41f9eb36bd8c > div.pbs-ui-hub.cta-enabled.paging-disabled.transition-disabled.metadata-disabled.title-disabled.videoTeasers-disabled.splashLogo-disabled.borderRadius-disabled:nth-child(3) > div.pbs-cta.pbs-cta-fullscreen:last-child\nsfgate.com###exp_b0d52c5c-8ef9-44e0-90ab-41f9eb36bd8c\nkedglobal.com###wrap > div.cookies_layer:nth-child(9)",
            "disabled-rules": ""
        },
        "allowlist": {
            "enabled": true,
            "inverted": false,
            "domains": [
                "www.facebook.com"
            ],
            "inverted-domains": []
        }
    }
}
```

</details>
