### ISSUE TITLE
Safari converter issue with "EasyList Cookie List"

### ISSUE THREAD

**Issue by Charlie102308** [AdguardTeam/AdGuardMiniForMac#685]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 1.10.4
* **Environment name and version:**
  * Version 15.2 (17612.3.6.1.6)
* **Operating system and version:**
  * MacOS 12.1
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Screenshots

<img width="912" alt="Screenshot 2022-02-14 at 18 52 25" src="https://user-images.githubusercontent.com/94617775/153851161-db3bc5aa-bb6a-4708-bdb4-fa8420455c0c.png">

<details><summary>Screenshot:</summary>

</details>

**Comment by tvinzz** [comment]
@Charlie102308, thank you for your report. Could you please provide the logs?

**Comment by tvinzz** [comment]
@Charlie102308, the problem is with `EasyList Cookie List`.
Please disable it temporary. We'll fix asap.

**Comment by tvinzz** [comment]
@Charlie102308, issue fixed.
`EasyList Cookie List` compiles well.
Update filters If the error still occurs.

**Comment by Charlie102308** [comment]
The EasyList Cookie List compilation failed agai
<img width="928" alt="Screenshot 2022-02-21 at 14 54 27" src="https://user-images.githubusercontent.com/94617775/154904058-b9d92c51-68d8-4cda-ac15-88daa0914fb2.png">
[adg_safari_logs_1645426552249.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/8106889/adg_safari_logs_1645426552249.zip)
n

**Comment by tvinzz** [comment]
@Charlie102308, please update filters
