### ISSUE TITLE
Compilation failed Social Filter

### ISSUE THREAD

**Issue by SkulduggeryOne** [AdguardTeam/AdGuardMiniForMac#686]
Hello, 
in the subject the error message on social media filter.
Safari 15.3, AdGuard version 1.10.4

With kind regards
ufo2010

**Comment by vozersky** [comment]
@SkulduggeryOne Hi, thanks for report, we are already looking into this issue. [Here](https://github.com/AdguardTeam/AdGuardForSafari/issues/685).
