### ISSUE TITLE
YouTube thumbnails stop loading

### ISSUE THREAD

**Issue by ncodee** [AdguardTeam/AdGuardMiniForMac#690]
### Issue Details

* AdGuard for Safari version: Safari 15.4 (17613.1.17.1.6)
* Environment name and version: AdGuard for Safari 1.10.4
* Operating System: macOS Monterey 12.3
* Filters you use in AdGuard: AdGuard Base filter, Tracking Protection filter, Annoyances filter, Online Malicious URL Blocklist, Filter unblocking Search ads & self-promotions

### Expected Behaviour
YouTube thumbnails to load normally.

### Actual Behaviour
After a while, the thumbnails on YouTube fail to load on some pages, I have to always clear cache on Safari, or toggle the AdGuard extension from time to time.

### Additional Information
I've noticed it happens on YouTube website, but may occur on other sites. Also, this happens randomly, and is very frustrating to say the least.

**Comment by Birbber** [comment]
@ncodee Could you check on the latest beta version? I can't reproduce it.

**Comment by Birbber** [comment]
@ncodee Any news?

**Comment by ncodee** [comment]
> @ncodee Could you check on the latest beta version? I can't reproduce it.

How would I opt-in to the beta?

**Comment by Birbber** [comment]
@ncodee It's already available on [GitHub](https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.11.3-beta). And we're expecting the release version soon.

**Comment by ncodee** [comment]
> @ncodee It's already available on [GitHub](https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.11.3-beta). And we're expecting the release version soon.

Thanks, so far the issue has persisted yet with the latest update. I will report back if anything changes.

**Comment by ncodee** [comment]
Update: The issue has re-appeared again unfortunately, on the latest version.

**Comment by Birbber** [comment]
@ncodee Could you try testing disabling all the filters? I suspect there might be an issue with one of them.
If it works fine please try disable filters one by one to identify the troubling one.
