### ISSUE TITLE
"Adguard needs your permission" after boot (on macos Monterey)

### ISSUE THREAD

**Issue by woefi** [AdguardTeam/AdGuardMiniForMac#700]
* AdGuard for Safari version: 1.11.3
* Environment name and version: Safari Version 15.4 (17613.1.17.1.13)
* Operating System: macOS Monterey 12.3.1 (21E258)
* Filters you use in AdGuard:
* Any other browser extensions you have installed: Ghostery (deactivated)

### Expected Behavior
"Silent" startup after boot

### Actual Behavior
Window is displayed: "Adguard for Safari needs your Permission" 
Pressing the "open Preferences" Button does nothing
opening the Safari preferences and unchecking and re-checking the extensions does not help 

### Screenshots
<img width="1072" alt="Bildschirmfoto 2022-04-04 um 11 19 52" src="https://user-images.githubusercontent.com/70533823/161514574-3fb8cf69-e6bc-4354-94ee-0848cd9d643a.png">

**Comment by woefi** [comment]
I have to add:
This only happened on my machines where I have two boot partitions (10.14 mojave and 12.3.1 monterey) and the other one is not updated yet.

I guess, eomehow at boot time AdGuard or macOS starts the wrong .app from the wrong drive.
So maybe there is a flaw in how the binary gets selected. It maybe just the first available one, regardless if it's in `/Applications` or `/Volumes/Drive2/Applications`

**Comment by Birbber** [comment]
@woefi Hi! Sorry for the late reply.
To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:

- Make sure all Safari content blockers are enabled;
- Reproduce the issue and remember the exact time when it happened;
- Open the extension settings --> Export logs and system info;
- Send the archive to `apple@adguard.com` and mention this issue number in the subject.

Also that would be nice if you could share a crash report from a system console.

**Comment by Birbber** [comment]
@woefi Have you already sent it?

**Comment by Birbber** [comment]
I'm closing this issue due to no response. Please re-open it if needed.
