### ISSUE TITLE
fandom.com - filtering works not on all pages

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardMiniForMac#701]
@adguard-bot commented on [Mon Mar 21 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393)

### Issue URL (Ads)
 [http://fandom.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Ffandom.com)
### Comment
Username: @DoctorX101
> This is a recent phenomenon. Blocking the frames does not work.
> 
> This appears to affect all individual fandom.com pages.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/y1RwWXv.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/J6r7HGZ.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Safari v1.10.4
Browser: | Safari
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>EasyPrivacy, <br/>Fanboy's Anti-Facebook List<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media, <br/>Fanboy's Social Blocking List<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Fanboy's Annoyances, <br/>Adblock Warning Removal List, <br/>I don't care about cookies<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/>Filter unblocking search ads and self-promotion, <br/>AdGuard DNS
Other extensions used: | AdBlock

---

@Apious commented on [Mon Mar 21 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1073477762)

||googletagservices.com^
||google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js
||scorecardresearch.com/beacon.js$script,redirect-rule=scorecardresearch.com/beacon.js
||quantserve.com^
||ak.sail-horizon.com^
||ad.gt^

fandom.com##+js(set-constant, wgAffiliateEnabled, false)
fandom.com##.top-ads-container
fandom.com##div.ad-slot-placeholder
fandom.com##div.top-ads-container

---

@DoctorX101 commented on [Mon Mar 21 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1073479595)

Apologies, but is that the code to include in the User Filters?

If that is the case, it does not seem to work.

---

@Alex-302 commented on [Mon Mar 21 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1073831154)

Cannot reproduce with your settings. 
Please try to disable-enable content blockers in Safari settings and restart Safari, and check for filters update.
Do not close AdGuard window 30-60 seconds, because iOS will breaks configuration process.

---

@DoctorX101 commented on [Sat Apr 02 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1086611277)

This did not occur on iOS but on the native computer.

Your suggestions, unfortunately, do not address the problem.

Reopening this.

---

@adguard-bot commented on [Sat Apr 02 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1086612373)

### Issue URL (Annoyance)
 [http://fandom.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Ffandom.com)
### Comment
>  Alex-302 commented 12 days ago
> 
> Cannot reproduce with your settings.
> Please try to disable-enable content blockers in Safari settings and restart Safari, and check for filters update.
> Do not close AdGuard window 30-60 seconds, because iOS will breaks configuration process.
> __________-
> This is not on iOS but on Monteray 12.3.
> 
> That suggestion, while not completely relevant to Monterey, does not work.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/VU5wTf2.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/xSB8KLT.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Safari v1.10.4
Browser: | Safari
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>EasyPrivacy, <br/>Fanboy's Anti-Facebook List<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media, <br/>Fanboy's Social Blocking List<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Fanboy's Annoyances, <br/>Adblock Warning Removal List, <br/>I don't care about cookies<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/>Filter unblocking search ads and self-promotion, <br/>AdGuard DNS
Other extensions used: | AdBlock

---

@Alex-302 commented on [Tue Apr 05 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1088253046)

Please click on this icon and tell us which ad system is it(looks like google ads, which must be blocked)
![image](https://user-images.githubusercontent.com/8361299/161678215-d396032e-d125-47cc-a413-a105e1697a49.png)

---

@DoctorX101 commented on [Tue Apr 05 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1088338780)

Thank you.

You are absolutely correct, which is weird since google ads are blocked on other pages.

---

@Alex-302 commented on [Thu Apr 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1090887005)

Same ads must be blocked anywhere.
Do you haму own rules or exclusions?

---

@DoctorX101 commented on [Thu Apr 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1090909355)

I may not understand your question. 

I assumed Google Ads were blocked by default on **AdGuard**. 

Anyway, if you look at that frame, and block it with **AdGuard**, you get a successful removal. The rule generated is:

watamote.fandom.com###top_leaderboard
watamote.fandom.com##div.main-container:nth-child(4) > div.top-ads-container:first-child

obviously, one could make that generic for other fandom.com pages, but on refresh or revisiting the main page of any Fandom.com, it comes back. So I guess I have the filter wrong.

You probably do not want to know that it successfully and reversibly blocked by **uBlock** for **Firefox**. Just for the Hell of it, I checked to see what **uBlock** is actually blocking:

||google-analytics.com^ www.google-analytics.com/analytics.js

among a veritable crapload of other scripts, but I would suspect that is it?

I then waste an hour trying to create a rule that will work only to utterly fail.

Thanks for the help!

---

@Alex-302 commented on [Thu Apr 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1091780938)

What I see without AdGuard for Safari
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/162217245-5f5b616b-5e2c-4627-89a8-d848a46e666e.png)

</details>

with AdGuard
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/162217514-d61545cc-6285-4b97-9090-bedfabcd4f91.png)

</details>

100% the problem is local. I would try to reinstall AdGuard after browser closing.

---

@DoctorX101 commented on [Thu Apr 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1091795465)

How does one do that?

I just removed AdGuard as an extension, closed the browser, reopened the browser, then added the extension, closed the browser, reopened the browser, and the problem persists.

---

@Alex-302 commented on [Thu Apr 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1091866590)

Weird. If you want, I can check it remotelly using AnyDesk app.

---

@DoctorX101 commented on [Thu Apr 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1091950625)

I thought AnyDesk is only compatible with Windows?

---

@Alex-302 commented on [Thu Apr 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1091991401)

Not only.
https://anydesk.com/ru/downloads/mac-os
If you agree, please send message to email in my profile.

---

@DoctorX101 commented on [Thu Apr 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113393#issuecomment-1092041549)

Unfortunately, security purposes will not allow that, though I appreciate the offer.

I can provide the complete listing of everything that is filtered, or part of it, provided I know what to look for beyond "google" and "fandom.com."

**Comment by Birbber** [comment]
@Alex-302 @DoctorX101 I wasn't able to reproduce the issue on my end.

**Comment by DoctorX101** [comment]
@Birbber Since it does occur, please be so kind as to indicate how you are filtering it.

**Comment by Birbber** [comment]
Ads are filtered even with only Base filter enabled: https://uploads.adguard.com/adguard_for_safari_on.png
Please try re-installing the application and updating the filters. Looks like a local issue.
