### ISSUE TITLE
AdvancedBlocking (CoreFoundation) error

### ISSUE THREAD

**Issue by mrlife** [AdguardTeam/AdGuardMiniForMac#716]
The following error occurs regularly and causes the page not to load after typing something in the Safari address/search bar and hitting enter.

> Couldn't read values in CFPrefsPlistSource<0x1370a7af0> (Domain: TC3Q7MAJXF.com.adguard.safari.AdGuard, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd

To reproduce:
1. Enable AdGuard for Safari extensions
2. Open a new tab
3. Enter text into address/search bar and press enter
4. Repeat steps 2-3, if needed, until issue presents

Version 1.11.4

**Comment by Birbber** [comment]
@mrlife Hi! Please share the app logs. Here's what we need you to do:

1. Make sure all Safari content blockers are enabled;
2. Reproduce the issue and remember the exact time when it happened;
3. Open the extension settings --> **Export logs and system info**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by Birbber** [comment]
@mrlife We've released a new version - [1.11.5](https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.11.5.215-release). Please check if the issue still reproducible.

**Comment by Birbber** [comment]
Closing this issue due to no reply. Please re-open if needed.

**Comment by mrlife** [comment]
@Birbber Hey, I updated to 1.11.6 and still see the issue.

**Comment by mrlife** [comment]
Possible to reopen? I don’t think I have the permission to do it.

**Comment by mrlife** [comment]
Hi @Versty, I sent those in on 6/21/2022.

**Comment by Versty** [comment]
@mrlife This issue in progress right now. Could you provide more info about:

- The version of macOS you're using
- Extension settings (attach screenshots if possible) 
- Where was this info located? (Console or something else) 
`Couldn't read values in CFPrefsPlistSource<0x1370a7af0> (Domain: TC3Q7MAJXF.com.adguard.safari.AdGuard, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd`
- Have you experienced the app crashes?

**Comment by mrlife** [comment]
> @mrlife Alright, please take a screenshots of an entire General and Filters tabs.

@Versty Thanks, I sent them in as a followup to the first email.

**Comment by Versty** [comment]
@mrlife ping

**Comment by Versty** [comment]
@mrlife We examined your logs and have not found any errors. 
You can make a clean installation, probably it would help. 

Follow the steps below to fully uninstall AdGuard for Safari: 
1. Uncheck all AdGuard for Safari extensions in **Safari -> Preferences -> Extensions** (if available)
2. Open **Finder** and press Shift+Command+G
    - Remove AdGuardSafariApp folder from **~/Library/Application Support** directory
    - Remove from **~/Library/Application Scripts** - all directories started with com.adguard.safari
    - Remove from **~/Library/Containers** - all directories started with AdGuard-
    - Remove TC3Q7MAJXF.com.adguard.safari.AdGuard folder from **~/Library/GroupContainers** directory
    - Remove com.adguard.safari.AdGuard.plist from **~/Library/Preferences** 
3. Open **Activity Monitor** and force quit all "cfprefsd" processes 
4. Remove AdGuard for Safari from **Applications**

**Comment by Versty** [comment]
@mrlife Has a clean installation resolved this issue?

**Comment by mrlife** [comment]
@Versty Hey, thanks for following up about this. I haven't seen the issue an a while and think it may have been something with Safari Tab Groups interfering.
