### ISSUE TITLE
[BUG] Wrong counting of rules in Safari 16.0 DB2

### ISSUE THREAD

**Issue by peterneutron** [AdguardTeam/AdGuardMiniForMac#732]
### Issue Details

* AdGuard for Safari version: 1.11.6 (216) 
* Environment name and version: Safari 16.0 (18614.1.16.11.3)
* Operating System: macOS Ventura 13.0 Beta (22A5286j)
* Filters you use in AdGuard: OISD Basic (https://abp.oisd.nl/basic/)
* Any other browser extensions you have installed: -

### Expected Behavior
Custom filters with =< 150k rules get added without error

### Actual Behavior
Custom filter with =< 150k rules trigger a warning and counting a negative number

### Screenshots
![adg](https://user-images.githubusercontent.com/60703175/176869377-bbded0a9-b08e-492b-93e9-73415b4c203d.png)

### Translation

The limit of 150000 rules has been exceeded. Please disable unnecessary rules to make the app work correctly.
Currently enabled rules: 59007 (-90993 rules disabled)

**Comment by Birbber** [comment]
@introns-bungles Hi! Do you have any other filter enabled except for the mentioned one?
Please also share the screenshot of the entire 'Content blockers' tab.

**Comment by introns-bungles** [comment]
@Birbber No, only OISD Basic.
![abp](https://user-images.githubusercontent.com/60703175/176876164-40121be2-8d8b-4d0b-99e9-beb28dd591e2.png)

**Comment by Birbber** [comment]
@introns-bungles Weird. Let's see the logs. Could you please collect them for us?

Here's what we need you to do:

1. Make sure all Safari content blockers are enabled;
2. Reproduce the issue and remember the exact time when it happened;
3. Open the extension settings --> **Export logs and system info**;
4. Send the archive to `apple@adguard.com` and mention this issue number and the time of reproduction in the subject.

**Comment by introns-bungles** [comment]
@Birbber Done.

**Comment by Versty** [comment]
@introns-bungles 
Awesome news! 
In case the issue returns please inform us and reopen this thread.

**Comment by yusoofsh** [comment]
I'm having this issue 🙏

![image](https://user-images.githubusercontent.com/18055365/180609696-cc7e1704-4c18-41f1-b405-f5d3815d7326.png)

**Comment by introns-bungles** [comment]
@Versty I can confirm that the issue returned with the jump from macOS `22A5295h` ->  `22A5295i`. Which is very weird because Safari stayed on the same version and I really can't imagine what would possibly cause this bug. But looking at the logs it seems that the rules get converted without a problem. Looks more like an UI Bug.

**Comment by Versty** [comment]
@

**Comment by Versty** [comment]
@introns-bungles @yusoofsh 
The issue reproduces on our side too and we are currently working on it.

**Comment by iDjay** [comment]
The annoyance filter doesn't seem to work anymore with the current Safari Beta 16.0 (18614.1.22.1.2)

**Comment by Versty** [comment]
@iDjay Hi! Thanks for noticing. We are already working on it.

**Comment by peterneutron** [comment]
@Versty Appears to be fixed with `1.11.7 (220)`. If others can confirm I think this can be closed.

**Comment by Versty** [comment]
@peterneutron Currently it is not reproducing on our side either. 
@yusoofsh Is the issue still persisting on your device?

**Comment by Versty** [comment]
@yusoofsh Also, i would recommend you to temporarily switch from the beta to the release cannel. 
Please, perform an advanced uninstall and then install the release version from the App Store or from [this link](https://agrd.io/safari_release).

Follow the steps below to fully uninstall AdGuard for Safari: 
1. Uncheck all AdGuard for Safari extensions in **Safari -> Preferences -> Extensions** (if available)
2. Open **Finder** and press Shift+Command+G
    - Remove AdGuardSafariApp folder from **~/Library/Application Support** directory
    - Remove from **~/Library/Application Scripts** - all directories started with com.adguard.safari
    - Remove from **~/Library/Containers** - all directories started with AdGuard-
    - Remove TC3Q7MAJXF.com.adguard.safari.AdGuard folder from **~/Library/GroupContainers** directory
    - Remove com.adguard.safari.AdGuard.plist from **~/Library/Preferences** 
3. Open **Activity Monitor** and force quit all "cfprefsd" processes 
4. Remove AdGuard for Safari from **Applications**

**Comment by peterneutron** [comment]
@Versty Can confirm the issue is back on `macOS 13.0 Beta (22A5352e)` running `Safari 16.1 (18614.2.6.1.1)` and the AdGuard for Safari MAS version `1.11.7 (220)`.

**Comment by srcshelton** [comment]
@Versty I'm having the same issue on GA macOS 12.6 with AdGuard `Version 1.11.7 (220)`:

There's a title-bar in red stating 'Too many filters enabled. Safari cannot use more than 150000 rules in one group.' and the General -> Content Blockers view shows:

> AdGuard Privacy
The limit of 150000 rules has been exceeded. Please disable unnecessary rules for the app to work correctly.
Enabled rules at the moment: 51802 (disabled rules: -98198)
Enabled: AdGuard Tracking Protection filter, EasyPrivacy, Fanboy's Enhanced Tracking List and 4 more

**Comment by Brett-Best** [comment]
I’m getting this on:
macOS 12.6.1 (21G211) 
Safari Version 16.1 (17614.2.9.1.8, 17614)
Safari Technology Preview Release 155 (Safari 16.4, WebKit 17615.1.7.1)

> ### AdGuard Privacy
> The limit of 150000 rules has been exceeded. Please disable unnecessary rules for the app to work correctly.
Enabled rules at the moment: 51728 (disabled rules: -98272)
Enabled: AdGuard Tracking Protection filter, EasyPrivacy, Fanboy's Enhanced Tracking List and 1 more

Be potentially helpful if AdGuard would show how many filters are in each list.
> AdGuard Tracking Protection filter (xxx rules)
