### ISSUE TITLE
Too many filters enabled

### ISSUE THREAD

**Issue by kzqian** [AdguardTeam/AdGuardMiniForMac#757]
### Issue Details
* AdGuard for Safari version: 1.11.7 
* Environment name and version: Safari 16.1
* Operating System: macOS 12.6.1
* Filters you use in AdGuard: AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, AdGuard Chinese filter 
* Any other browser extensions you have installed: N/A

### Expected Behavior
Filters loaded

### Actual Behavior
Getting error message saying "Too many filters enabled. Safari cannot use more than 150000 rules in one group."

### Additional Information
It works fine with EasyList China replaces the AdGuard Chinese filter.

**Comment by Versty** [comment]
@kzqian hi! 
Seems like you've found a bug. Reproduced on our side and will be fixed as soon as possible.

**Comment by Versty** [comment]
@kzqian Should be fixed. 
Please check for filters update, then restart Safari.
