### ISSUE TITLE
"Some extensions are disabled" after a few days of using beta 

### ISSUE THREAD

**Issue by SeventhZ** [AdguardTeam/AdGuardMiniForMac#763]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard for Safari:**
  * 1.11.8(237)
* **Environment name and version:**
  * Safari 16.1 (18614.2.9.1.12)
* **Operating system and version:**
  * macOS 13.0.1 (22A400)
* **Filters you use in AdGuard:**
  * Base, Tracking Protection
* **Any other browser extensions you have installed:**
  * 1. Tampermonkey 2. Bitwarden 3. DarkReader

### Actual Behavior
After a few days of use, "some adguard extensions have been disabled" is displayed. But I have opened all the extensions related to adguard

### Screenshots
<img width="248" alt="CleanShot 2022-11-20 at 13 59 42@2x" src="https://user-images.githubusercontent.com/53437433/202888282-12e2f6c0-2590-48a3-8834-bc02187db7b2.png">
<img width="1072" alt="CleanShot 2022-11-20 at 14 00 45@2x" src="https://user-images.githubusercontent.com/53437433/202888307-acdfc4fd-2346-435d-8244-ebaf03d3219d.png">
<img width="886" alt="CleanShot 2022-11-20 at 14 07 38@2x" src="https://user-images.githubusercontent.com/53437433/202888491-e5101691-cb8f-495c-864e-6f5b0cef1148.png">

</details>

**Comment by SeventhZ** [comment]
I have installed the latest beta(241 build), but after a while, the issue has been returned.

<img width="1072" alt="CleanShot 2022-11-21 at 17 55 14@2x" src="https://user-images.githubusercontent.com/53437433/203020678-19c6bbdb-bb5b-4e92-ab30-47336c7fd43d.png">

**Comment by Versty** [comment]
@SeventhZ We've discussed this issue with the developers team. The best solution in this case might be a clean installation. 
So please uninstall completely and then install the latest beta version from the link above. 

Follow this steps to fully uninstall AdGuard for Safari: 
1. Uncheck all AdGuard for Safari extensions in **Safari -> Preferences -> Extensions** (if available)
2. Open **Finder** and press Shift+Command+G
    - Remove AdGuardSafariApp folder from **~/Library/Application Support** directory
    - Remove from **~/Library/Application Scripts** - all directories started with com.adguard.safari
    - Remove from **~/Library/Containers** - all directories started with AdGuard-
    - Remove TC3Q7MAJXF.com.adguard.safari.AdGuard folder from **~/Library/GroupContainers** directory
    - Remove com.adguard.safari.AdGuard.plist from **~/Library/Preferences** 
3. Open **Activity Monitor** and force quit all "cfprefsd" processes 
4. Remove AdGuard for Safari from **Applications**
