### ISSUE TITLE
got this error when clicking seek for update in safari

### ISSUE THREAD

**Issue by markryder0** [AdguardTeam/AdGuardMiniForMac#766]
[

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 
![adgarderror](https://user-images.githubusercontent.com/7074579/204073717-ef1da5ae-1890-46a6-90f9-77b779cc7603.png)

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Versty** [comment]
@markryder0 Hi! 
Could you provide info about the operating system and Safari version you are using? 
Does this issue reproduce every time when you click the `Check for updates` button? 

In addition, logs from your device would be extremely helpful for troubleshooting on our side. 
1. Make sure all Safari content blockers are enabled;
2. Reproduce the issue and remember the exact time when it happened;
3. Open the extension settings --> **Export logs and system info**;
4. Also **Export settings**
5. Send the logs archive and settings file to `apple@adguard.com` and mention this issue number in the subject.

**Comment by markryder0** [comment]
Think I might have been the prior free installation of the safari plugin as I notice I had two icons for the product so deleted one and rebooted it seems ok ow but will inform if I get another error 
Apple M1 Ventura 13.0.1 (22A400)

**Comment by Versty** [comment]
@markryder0 Got it, please keep me posted!
