### ISSUE TITLE
Cosmetic rules without domain name not applied anymore to all websites

### ISSUE THREAD

**Issue by Shnub** [AdguardTeam/AdGuardMiniForMac#767]
Starting with some recent version of AdGuard for Safari (probably it was the 1.11.8 update, but not entirely sure), cosmetic rules without a domain name (using the "Apply the rule to all websites" option) are not applied anymore. That is:

`###someid`

or

`##.someclass`

won't hide elements with id `someid` or with class `someclass` on any webpages anymore.

It's easy to reproduce:

### Steps to reproduce

1. Visit duckduckgo.com. (Just an example, the issue is not website-specific.)
2. Use AdGuard's element blocker to select the central DuckDuckGo logo such that `duckduckgo.com###logo_homepage_link` is used as the blocking pattern.
3. Click "Block".
4. The element is now hidden and stays that way.
5. Now go to the User filters, remove "duckduckgo.com" from the pattern (such that it is now just `###logo_homepage_link`) and save.
6. Wait until the pattern has been incorporated into AdGuards content blocking (always takes a minute or so for me).
7. Reload the page.
8. The logo is back again.

The same thing happens when the logo is blocked by class instead of by id.

Curiously, when the pattern is entered through the element blocker and "Apply to all websites" is clicked, the _preview_ will work correctly and and the element will stay hidden for about a minute... but then appear again!

### Your environment
* Environment name and version: macOS 12.6.1, Safari 16.1, AdGuard for Safari 1.11.8
* Any specific potentially conflicting software installed: none (no other content/ad blockers installed)

**Comment by Aydinv13** [comment]
@Shnub your issue was moved to the right repository.

**Comment by Versty** [comment]
@Shnub Hi! Let's find the root of this issue. 
Was your version of AdGuard for Safari installed from AppStore or via the product link?

**Comment by Versty** [comment]
@Shnub Thank you for the detailed explanation. 
It would be helpful if you could export your settings and send it to our e-mail `apple@adguard.com`.
Please mention in the subject this issue number - `#767`.

**Comment by Versty** [comment]
@Shnub I don't think using BBEdit helped in some way. 
Please reopen this thread if the issue returns.
