### ISSUE TITLE
forums.macrumors.com - protection does not work on MacBook Air M2 [there is also issue on other websites]

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardMiniForMac#774]
@adguard-bot commented on [Tue Dec 06 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136762)

### Issue URL (Ads)
 [https://forums.macrumors.com/threads/adguard-not-working-last-couple-of-days.2361196/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fforums.macrumors.com%2Fthreads%2Fadguard-not-working-last-couple-of-days.2361196%2F)
### Comment
Username: @will-wren
> AdGuard blocks no ads at all on MacBook Air M2, version 13.0.1 (22A400)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/cwe14Rv.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Safari v1.11.8
Browser: | Safari
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection
Other extensions used: | No other ad blockers used, it doesn't block any ads from what I can see. I have Keepa and Bitwarden extensions

---

@zloyden commented on [Tue Dec 06 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136762#issuecomment-1338951118)

Not reproduced it on my end.
Try to clear browser data, restart it, update the filters (wait almost one minute there), open the site.
If that doesn't work, you should re-enable the content blockers in Safari settings (wait about the same time as when you update the filters).

---

@will-wren commented on [Tue Dec 06 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136762#issuecomment-1338964494)

@zloyden thanks for the reply. The above steps did not solve the issue, any other ideas?

---

@zloyden commented on [Tue Dec 06 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136762#issuecomment-1339011189)

That's strange, but I noticed, that you have been using AdGuard for Safari on MacBook Air M2. I don't have it and checked on MacBook that's based on Intel CPU. Maybe it's issue with the app.
For instance, the top banner is removed by this rule `macrumors.com##.tertiary`. Can you add the rule to the User rules (you should also wait for the rule to be applied for ~ one minute) and check the site in private tab?
Do you have any rules for this site? Is it on allow list?

---

@will-wren commented on [Tue Dec 06 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136762#issuecomment-1339102506)

No custom rules  or allows on any site, fresh AdGuard install. I noticed it does work on YouTube - removes video ads and ones at side of video, however on most other sites it doesn't remove any ads.

I tried adding the rule manually for macrumours but no luck, still get ads!

---

@zloyden commented on [Tue Dec 06 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136762#issuecomment-1339139442)

> however on most other sites it doesn't remove any ads

That's really strange behaviour and might be related to the app.
Could you please show the html code of the element?
1. Do right click on the banner like in the screenshot and select Inspect the object (it's blocked on my end)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/205890831-be1b380e-d3e8-4d9d-8bec-b098e54afafd.png)

</details><br/>
2. In the elements column search ".tertiary". When you find it, take a screenshot and send it here. My screenshot above shows the expectated behaviour, but yours should be different.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/205891148-4473159c-911f-43e4-b1dd-169ba6d59e70.png)
</details><br/>

---

@will-wren commented on [Mon Dec 12 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136762#issuecomment-1345378834)

Hello, is this what's needed? Thanks
<details><summary>Screenshot:</summary>

<img width="1280" alt="Screenshot 2022-12-10 at 20 29 53" src="https://user-images.githubusercontent.com/119923877/206874168-52b535ad-9280-4ffc-961b-648b682e0405.png">
</details><br/>

---

@zloyden commented on [Mon Dec 12 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136762#issuecomment-1345954443)

Yes. Looks like your protection does not work at all. This element is blocked by AdGuard Base. I will move this task to another repository.

**Comment by zloyden** [comment]
@will-wren the task is moved to this repository [AdGuardForSafari](https://github.com/AdguardTeam/AdGuardForSafari). Be prepared to answer the developers' questions.

**Comment by Versty** [comment]
@will-wren Hi! 
Please disable other Safari extensions (Safari -> Preferences -> Extensions) and check again if ads are blocked by the AdGuard Base filter.

**Comment by will-wren** [comment]
Hi @Versty thanks for your reply. Still no ads blocked with all other extensions disabled I'm afraid. Will

**Comment by Versty** [comment]
@will-wren Let's find out what went wrong. 
Could you export the logs, settings and send them to our email `apple@adguard.com`? Please mention the number `#774` in the subject.

**Comment by Versty** [comment]
@will-wren Any updates?

**Comment by will-wren** [comment]
@Versty I was away for Christmas. How do I export those things? Thanks

**Comment by Versty** [comment]
@will-wren Launch AdGuard for Safari. Open Preferences -> General tab -> scroll down to the bottom of the tab, use both Export logs and Export setting options.

**Comment by will-wren** [comment]
Hi Diana,

Sorry I haven’t as my MacBook isn’t charging at all. Going to Apple Store today to sort it.

Thanks for your patience.

Cheers,
Will

**Comment by Versty** [comment]
@will-wren Hi!
In this case, it would be better to close this issue until your Mac is back in operation. 
Feel free to reopen this thread and continue discussion when you are ready.

**Comment by will-wren** [comment]
Hi Diana,

That MacBook stopped charging completely so I got a new one and AdGuard
seems to work. Unsure what is different as it's set up the same as before.

Cheers,
Will
