### ISSUE TITLE
Random update alert window

### ISSUE THREAD

**Issue by rickwierenga** [AdguardTeam/AdGuardMiniForMac#778]
Hi,

Every day AdGuard prompts me to update, even though I have all update settings turned off. When I click "cancel", the app is opened (the other option is to close Safari). I have tried updated the app multiple times, but the issue comes back with each new version. What's going on here? Let me know if you need additional information.

<img width="949" alt="Screen Shot 2022-12-22 at 4 36 43 PM" src="https://user-images.githubusercontent.com/36956818/209230436-7f15984b-c069-4bf7-a294-1a94ea4c0ad0.png">

**Comment by Versty** [comment]
@rickwierenga Hi! 

Could we take a look into your logs? 
Please, collect it via in-app option and send to `apple@adguard.com` mentioning the issue number `#778` in the subject.

**Comment by Versty** [comment]
@rickwierenga Did you send the logs?

**Comment by rickwierenga** [comment]
Just did.

**Comment by Versty** [comment]
@rickwierenga We are currently working on changes related to notifications.
Could you please provide the screenshot of the reminder you were talking about?

**Comment by rickwierenga** [comment]
Amazing!

The reminder has actually not appeared recently, now it just opens the settings window. Before that it was a "default-style" alert asking whether I want to update.

From #790:

> Extend the new update notification period to one week after the previous update notification was discarded.

Just to be explicit: my problem was actually that I want to turn it off completely.

**Comment by Versty** [comment]
@rickwierenga Seems like our application has no code to trigger this reminder, it actually may be a part of App Store's update reminders. Could you recall if there was an App Store or AdGuard icon in the reminder?
