### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Robert3999** [AdguardTeam/AdGuardMiniForMac#780]
I find it very hard to download the new up dates. I keep getting instructions to delete the extensions even though I have quit adguard. very annoying. Can you help?

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Versty** [comment]
@Robert3999 In fact, if you see this kind of notifications, I would recommend you to delete the app and install the latest version. 
You can download it from the App Store or directly via [this link](https://agrd.io/safari_release).
