### ISSUE TITLE
Alternative methods of uninstalling without unloading Safari extensions

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardMiniForMac#781]
When uninstalling any macOS app or macOS extension, it's almost always as easy as dragging the app to the bin which begins the designed process of uninstalling all related items (extensions and such), presuming Safari is closed.

I've uninstalled AdGuard for Safari often enough for testing for it to be puzzling to me as to why it's like this when I've never experienced it before.

I'm sure there's a good reason, but is there a problem that can't be solved here without manual intervention from the user that Apple hasn't solved yet, or something else?

**Comment by Versty** [comment]
@jslawler Alternatively, you can quit Safari and then drag and drop AdGuard for Safari application to the bin.

Could you name any other Safari extension that you can remove without unchecking the extension checkbox or quitting Safari?

**Comment by jslawler** [comment]
Apologies Diana, I was mistaken. I must have had something else in my mind when I was thinking about uninstalling extensions without unticking them.

As a side note to your first sentence, quitting Safari then dragging and dropping the app to the Bin shouldn't work for ANY Safari extension as the system keeps the extension process loaded until unticked.
I tested this with Bitwarden and AdGuard for Safari on the latest Safari stable and the preview.

If this is not expected, I guess that can be something that can be improved. :)

**Activity Monitor with Safari running**
<img width="1072" alt="Screenshot 2022-12-29 at 5 29 25 pm" src="https://user-images.githubusercontent.com/95468948/209918249-06ae86fa-ca75-4cf0-a88b-b628e1a9ac0d.png">

**Activity Monitor with Safari quit**
<img width="1072" alt="Screenshot 2022-12-29 at 5 29 44 pm" src="https://user-images.githubusercontent.com/95468948/209918290-8694dd8d-60ca-4418-923a-c249f40d1ca9.png">

**Comment by Versty** [comment]
@jslawler AdGuard processes should be closed in 30-40 seconds after quitting Safari.

**Comment by jslawler** [comment]
To confirm, having the extensions ticked or unticked should have no effect on the processes closing after that time?

As it stands, the extensions are still ticked, and I've left it for 10 minutes with Safari quit, and the AdGuard for Safari processes are still running in the background.

macOS: Version 13.2 (a) Beta (22D7750270d)
Safari: Version 16.2 (18614.4.1.500.1)
AdGuard for Safari: Version 1.11.9 (build 262, CT 2.0.34)

**Comment by jslawler** [comment]
Disregard, after reinstalling, AdGuard for Safari worked as you described.
Instead of taking 30-40 seconds, it was within 1 seconds.

**Comment by Versty** [comment]
@jslawler Happy to hear that everything is working as expected on your device!
