### ISSUE TITLE
AdGuard window keeps popping up

### ISSUE THREAD

**Issue by kyellareddy** [AdguardTeam/AdGuardMiniForMac#791]
Every once in a while, the "AdGuard For Safari" app window will open itself and switch me away from whatever app I was using.

Instead of having the window automatically open when there's an update, maybe the app could send a notification; you could also make a menu bar icon for AdGuard that shows a red badge on it when there's something that requires the user's attention similar to the Adobe Creative Cloud menu bar icon.

**Comment by Versty** [comment]
@W00dyBuzz Hi!
Update to the latest version or clean installation fixes this issue. 

Follow the steps below to fully uninstall AdGuard for Safari: 
1. Uncheck all AdGuard for Safari extensions in **Safari -> Preferences -> Extensions** (if available)
2. Open **Finder** and press Shift+Command+G
    - Remove AdGuardSafariApp folder from **~/Library/Application Support** directory
    - Remove from **~/Library/Application Scripts** - all directories started with com.adguard.safari
    - Remove from **~/Library/Containers** - all directories started with AdGuard-
    - Remove TC3Q7MAJXF.com.adguard.safari.AdGuard folder from **~/Library/GroupContainers** directory
    - Remove com.adguard.safari.AdGuard.plist from **~/Library/Preferences** 
3. Open **Activity Monitor** and force quit all "cfprefsd" processes 
4. Remove AdGuard for Safari from **Applications**

Then download and install the application from the [App Store](https://agrd.io/safari) or via the [direct link](https://agrd.io/safari_release). 

If you would like to discuss this issue further, please continue in #746
