### ISSUE TITLE
Every time I boot up my macbook pro each morning, the Ad Guard for Safari settings come up. 

### ISSUE THREAD

**Issue by londonroadhog** [AdguardTeam/AdGuardMiniForMac#804]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 1.11.11 (build 275, CT 2.0.34)

### Environment

```markdown
- OS:Ventura 13.2.1 (22D68)
- Safari version:16.3 (18614.4.6.1.6)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter

### Issue Details

Steps to reproduce:
1. Shut down in the evening
2. Turn on in the morning.
3. Sign into the computer, and Adguard for Safari settings/options are shown after a few seconds. I have to close it every time.

### Expected Behavior

I don't expect to have to close the Ad Guard for Safari window every morning.

### Actual Behavior

Just said this.... The Ad Guard for Safari window appears every morning after booting up the Macbook Pro.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by jslawler** [comment]
#746

**Comment by Versty** [comment]
@londonroadhog Hi! 
Please continue discussion in `#746`.
