### ISSUE TITLE
Launch in the background

### ISSUE THREAD

**Issue by TigerCat-hu** [AdguardTeam/AdGuardMiniForMac#805]
### Issue Details

Before the update, the app started in the background. It now appears on my desktop after startup. How can it be start in the background?

![AdGuard_start](https://user-images.githubusercontent.com/33827733/220270331-59844481-2230-479f-bd2c-5aac0371e14c.png)

**Comment by jslawler** [comment]
#746

**Comment by Versty** [comment]
@TigerCat-hu Hi! 
We are looking for a solution. This issue reproduces on the builds dowloaded from App Store. As a temporary measure we would suggest you to install the latest AdGuard for Safari version directly from [this link](https://agrd.io/safari_release). 
Please uninstall first, then download and install.

**Comment by caasols** [comment]
The workaround described here solved my problem. Thank you!

**Comment by Versty** [comment]
@TigerCat-hu @jslawler @caasols  Some good news for today.
This issue should be gone in the latest beta, already available in the TestFlight. Feel free to join and test it with us!  
Use [this link](https://agrd.io/adguard_for_safari_testflight) to participate as a beta tester.

**Comment by jslawler** [comment]
> @TigerCat-hu @jslawler @caasols  Some good news for today.
> 
> This issue should be gone in the latest beta, already available in the TestFlight. Feel free to join and test it with us!  
> 
> Use [this link](https://agrd.io/adguard_for_safari_testflight) to participate as a beta tester. 

@Versty everything is all good on my end. 5 reboots and no issues.

**Comment by TigerCat-hu** [comment]
Wow, thanks!
😀
I'm looking forward to the app store version.
Thank you!
