### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by TheBlueRage** [AdguardTeam/AdGuardMiniForMac#806]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.11

### Environment

```markdown
- OS: Monterey 12.6.3
- Safari version: 16.3
```

### Issue Details

Steps to reproduce:
1. Click check for updates
2.
3.

### Expected Behavior

Expected filters to update

### Actual Behavior

Filter update failed

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

[adg_safari_logs_1677025449015.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/10798939/adg_safari_logs_1677025449015.zip)

**Comment by D13410N3** [comment]
Issue was fixed some hours ago, could you please check?
