### ISSUE TITLE
AdGuard's settings window on login

### ISSUE THREAD

**Issue by tate1435** [AdguardTeam/AdGuardMiniForMac#807]
### AdGuard Extension version

1.11.11

### Browser version

Safari

### OS version

macOS 13.2

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

The settings window opens when I log into my laptop. I did a small search and found a couple of users with the same issue over on reddit. I've deleted the extension and reinstalled but it didn't help.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@tate1435 Hi! 
This bug is known and will be fixed #805.  As a temporary solution you can download and install the latest AdGuard for Safari version from [this link](https://agrd.io/safari_release).
