### ISSUE TITLE
Contents blockers disabled, and no way to enable them

### ISSUE THREAD

**Issue by ajay-gh** [AdguardTeam/AdGuardMiniForMac#827]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.11

### Environment

```markdown
- OS: Monterey 12.6.2
- Safari version: 16.3

After installation of the Adguard software, without any signs of problems, the main Adguard window shows that all contents blockers are disabled. Under "general" there is a button called "fixit" shown, which looks as if it's trying to address this problem. But it's mute, and doesn't do anything.
```

### Issue Details

Steps to reproduce:
1. just install it
2. no other steps
3.

### Expected Behavior

obvious !

### Actual Behavior

as explained above

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ajay-gh** [comment]
here is a screenshot
<img width="878" alt="Screen Shot 2023-03-14 at 3 22 43 PM" src="https://user-images.githubusercontent.com/46941311/225031515-c9e642a5-260c-443f-8691-b0ff724a5213.png">

**Comment by ajay-gh** [comment]
Also verified that this isn't a osx gatekeeper issue.

**Comment by Versty** [comment]
@ajay-gh Feels like something went wrong on your device locally. 
Clean install should fix the issue. 

Please, follow the steps below to completely uninstall AdGuard for Safari: 

1. Uncheck all AdGuard for Safari extensions in **Safari -> Preferences -> Extensions** (if available)
2. Remove AdGuard for Safari from **Applications**
3. Open **Finder** and press Shift+Command+G
    - Remove AdGuardSafariApp folder from **~/Library/Application Support** directory
    - Remove from **~/Library/Application Scripts** - all directories started with com.adguard.safari
    - Remove from **~/Library/Containers** - all directories started with AdGuard-
    - Remove TC3Q7MAJXF.com.adguard.safari.AdGuard folder from **~/Library/GroupContainers** directory
    - Remove com.adguard.safari.AdGuard.plist from **~/Library/Preferences** 
4. Open **Activity Monitor** and force quit all "cfprefsd" processes 

Then download and install latest version from App Store or via [this link](https://agrd.io/safari_release).

**Comment by Versty** [comment]
@ajay-gh Does it resolve the issue?

**Comment by Versty** [comment]
@ajay-gh Closed due to lack of response. 
Please reopen if needed.
