### ISSUE TITLE
Issue with filter updating

### ISSUE THREAD

**Issue by PaulKhanin** [AdguardTeam/AdGuardMiniForMac#852]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.10.4

### Environment

```markdown
- OS: Monterey 12.0.1 (21A559)
- Safari version: 15.1 (17612.2.9.1.20)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, RU AdList - Counters

### Issue Details

Steps to reproduce:
1. Open app settings
2. Click Filters
3. Check update
4. Notification from app about Issue with filter updating

### Actual Behavior

Same

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/58819434/1b93a02a-85cc-4638-966f-ca1833e2ad57)

</details>

**Comment by Versty** [comment]
@PaulKhanin Hi! 
Please update the application to the latest version (1.11.13).

**Comment by PaulKhanin** [comment]
HI @Versty

Sorry, I couldn't see the app update in the AppStore (although I checked before posting this issue)
Rechecked again (time later...)

Thank you, all work on the new version

Have a nice day
