### ISSUE TITLE
Update Bug

### ISSUE THREAD

**Issue by Atalantia** [AdguardTeam/AdGuardMiniForMac#881]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.13

### Environment

```markdown
- OS: macOS 10.14.6
- Safari version: 14.1.2
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard German filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Other Annoyances filter

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

Updating without issues.

### Actual Behavior

After updating in AppStore the AppStore says. "Safari has to close for update". After closing Safari the AppStore continues nagging about closing Safari for infinite. Clicking Cancel will result to download the whole package again.
### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@Atalantia Have you tried rebooting your macOS? Please disable all content blockers related to AdGuard for Safari in the Safari settings (Safari -> Settings -> Extensions) and then reinstall AdGuard for Safari.

**Comment by alexx7311** [comment]
Has the problem been resolved? The issue will close in a few days if we don't receive a response from you.
