### ISSUE TITLE
Only two AdGuard extensions are displayed in Safari settings

### ISSUE THREAD

**Issue by Zuano** [AdguardTeam/AdGuardMiniForMac#888]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14

### Environment

```markdown
- OS: 13.5.2
- Safari version: 16.6
```

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

I only see two check marks to tick in the extension settings.

I expected to see several.

### Actual Behavior

I only see two check marks to tick in the extension settings.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

![Bildschirmfoto 2023-09-09 um 12 07 36](https://github.com/AdguardTeam/AdGuardForSafari/assets/33006608/db883470-7320-4df9-b492-470b3d28a968)
![Bildschirmfoto 2023-09-09 um 12 07 18](https://github.com/AdguardTeam/AdGuardForSafari/assets/33006608/c6e8cd66-4c1d-4160-a885-89c106b115a8)

**Comment by alexx7311** [comment]
@Zuano Please go to Safari -> Settings -> Extensions and temporarily untick all extensions, then reinstall the app. Did that help?

**Comment by Zuano** [comment]
Today all the checkboxes were there again. 
I still unticked it and reinstalled it.
I'll keep you posted on what comes out.

**Comment by alexx7311** [comment]
@Zuano We'll close the issue for now. If the problem reoccurs, please reopen the issue.
