### ISSUE TITLE
USA Today website detecting ad blocking again (was fixed 2 weeks ago)

### ISSUE THREAD

**Issue by jameyers4** [AdguardTeam/AdGuardMiniForMac#889]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14

### Environment

```markdown
- OS: Version 13.5.2 (22G91)
- Safari version: Version 16.6 (18615.3.12.11.2)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

Steps to reproduce:
1.Navigate to usatoday.com
2.if adblocker warning does not display, click to another tab or minimize Safari window and wait several minutes
3.

### Expected Behavior

AdGuard should not trigger adblocker warnings

### Actual Behavior

get adblocker warning page

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="1440" alt="Screenshot 2023-09-13 at 10 49 57 AM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/30449337/f593ba31-4c92-4ab7-b2f0-2ded63e9e54e">

</details>

### Additional Information

exact same issue  that was fixed 2 weeks ago started happening today again.  

URL of last ticket:  https://github.com/AdguardTeam/AdguardFilters/issues/160339

**Comment by alexx7311** [comment]
@jameyers4 Please reopen the initial issue in filters repo https://github.com/AdguardTeam/AdguardFilters/issues/160339 
This issue is not related to AdGuard for Safari app.
