### ISSUE TITLE
Missed ads

### ISSUE THREAD

**Issue by joellevtov** [AdguardTeam/AdGuardMiniForMac#901]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.1.14

### Environment

```markdown
- OS:13.2.1 (22D68)
- Safari version: Version 16.3 (18614.4.6.1.6)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter

### Issue Details

Steps to reproduce:
1. Go to https://fmoviesz.to/tv/the-morning-show-j2j08/3-5
2. Play the video
3. Pause the video

### Expected Behavior

No ad should pop up

### Actual Behavior

An ad will appear towards the middle of the screen.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="1440" alt="Screenshot 2023-10-04 at 11 14 05 AM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/112434531/2d73786d-0510-4701-b830-26dbb12dbcbf">

</details>

**Comment by Versty** [comment]
@joellevtov Hi! 
Please report missed ads using in-app option "Report incorrect blocking" in the Support tab.

**Comment by joellevtov** [comment]
Hey @Versty! I tried to report it through that but it wouldn't let me upload pictures - it told me that the URL was invalid each time.
