### ISSUE TITLE
Safari 17 + AdGuard for Safari breaks DuckDuckGo

### ISSUE THREAD

**Issue by tallinn1960** [AdguardTeam/AdGuardMiniForMac#903]
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.4

### Environment

```markdown
- OS: Ventura 13.6
- Safari version: 17
```

### Issue Details

Steps to reproduce:
1. Search something on DuckDuckGo
2. Klick on a link offered by DuckDuckGo
3. Klick on the "Back" button of Safari to return to DuckDuckGo

### Expected Behavior

full functional DuckDuckGo-Page

### Actual Behavior

DuckDuckGo becomes unfunctional. One can no longer edit the search or scroll through the search results or click on another search result. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Tried workarounds, that did not work:
- Reload the DuckDuckGo page
- Disabling AdGuard for DuckDuckGo

Workaround, that worked:
- disabling all AdGuard extensions in Safari

This issue appeared after upgrading Safari to Version 17.

**Comment by alexx7311** [comment]
@tallinn1960 Hello! We couldn't reproduce the problem. Please uninstall the current version of AdGuard for Safari following the instructions at https://adguard.app/kb/adguard-for-safari/installation/#uninstall

Disable all other extensions in Safari and restart the browser. Then install newly released 1.1.15 version https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.11.15.309-release

Did that solve the problem?

**Comment by tallinn1960** [comment]
I did as you requested and it looks like this resolved the problem. So now I am running 1.11.15 with standard settings (I only changed the settings to start AdGuard on login). Other extensions used where Paradox “Open in Internet Explorer” and Webex. I disabled them prior to removing, reinstalling and testing AdGuard, but now, with them enabled again, the tests are still green.

Thank you
Tallinn
