### ISSUE TITLE
App did not auto launching after restarting

### ISSUE THREAD

**Issue by helloimvictorchor** [AdguardTeam/AdGuardMiniForMac#908]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14

### Environment

```markdown
- OS: Sonoma 14
- Safari version: 17.0 （19616.1.27.211.1）
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter

### Issue Details

Steps to reproduce:
1. Restart Mac
2. Logged in account of Mac
3. App didn't auto launching
4. I launching it manually

### Actual Behavior

I noticed that after I restart my Mac, and logged to my account of my Mac, your app did not auto launching.

I have enabled Launch AdGuard for Safari at Login settings. 

I found this problem is that extension of Safari showing paused. 

### Screenshots

<details><summary>Screenshot 1:</summary>

![CleanShot 2023-10-08 at 14 49 36@2x](https://github.com/AdguardTeam/AdGuardForSafari/assets/87065622/d495848d-22c8-41c2-a33d-7628e60c4261)

</details>

**Comment by alexx7311** [comment]
@victorchor2868 The issue will be closed in a few days if we do not hear back from you.

**Comment by alexx7311** [comment]
@victorchor2868 We'll close the issue for now, but if the problem recurs, please reply in the comments. Please note that now the app window no longer appears at system startup.
