### ISSUE TITLE
web app 

### ISSUE THREAD

**Issue by safir96** [AdguardTeam/AdGuardMiniForMac#914]
### Issue Details

**web app** is basically safari but adguard app is not working on the **web app** ** like if you add web app youtube on your doc it show too many ads on it but if you  open **youtube** in safari there will be no ads on it i hope your team will find way  to add extensions on web apps  like **Instagram**  **youtube**  **google**  

### Proposed solution

add adguard to web app extensions

**Comment by Versty** [comment]
@safir96 Hi! 
This issue duplicates #872.
