### ISSUE TITLE
Ads on AT&T's Yahoo Mail

### ISSUE THREAD

**Issue by Opinari2** [AdguardTeam/AdGuardMiniForMac#921]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.15

### Environment

```markdown
- OS: Sonoma 14
- Safari version: 17
```

### Issue Details

Steps to reproduce:
1. Auto blocking on
2.Launch at login
3.Check to see if on

### Expected Behavior

Blocking ads on Safari including AT&T's Yahoo Mail.

### Actual Behavior

Not blocking AT&T's Yahoo mail. 
Haven't noticed on other sites.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I do not have any.

**Comment by Opinari2** [comment]
All filters that apply are on

**Comment by Opinari2** [comment]
Not completed

**Comment by Opinari2** [comment]
No information or fix forthcoming. Nothing changed.

**Comment by Opinari2** [comment]
Comment button not working.

**Comment by alexx7311** [comment]
@Opinari2 Hello! Please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
