### ISSUE TITLE
AdGuard randomly opens.

### ISSUE THREAD

**Issue by KarlBunker** [AdguardTeam/AdGuardMiniForMac#925]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14 (build 301, CT 2.0.41)

### Environment

```markdown
- OS: Latest
- Safari version: Latest
```

### Issue Details

Steps to reproduce:
1.
2.
3.

### Actual Behavior

At random times through the day, AdGuard launches in the foreground. I don't see any reason why this would be happening.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@KarlBunker Hi! 
Please update to the latest version (1.11.15). This issue is already fixed.
