### ISSUE TITLE
App reopens every morning for some reason

### ISSUE THREAD

**Issue by molonlabe88** [AdguardTeam/AdGuardMiniForMac#933]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14

### Environment

```markdown
- OS: Sonoma 14.0
- Safari version: 17
```

### Issue Details

Steps to reproduce:
1. Leave computer alone in the evening
2. Log into computer in the morning
3. App is opened and in taskbar. 

### Expected Behavior

I expect the app to not reopen itself in my taskbar when i've closed it. 

### Actual Behavior

Its open in my taskbar

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by zzebrum** [comment]
@molonlabe88 please update app to [the latest version](https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.11.15.309-release).
