### ISSUE TITLE
App window randomly opens

### ISSUE THREAD

**Issue by pizza496** [AdguardTeam/AdGuardMiniForMac#938]
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I made sure all content blockers are enabled in Safari settings
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14 (build 301, CT 2.0.41)

### Environment

```markdown
- OS: Sonoma 14.2 Beta (23C5030f)
- Safari version: 17.2 (19617.1.11.11.3)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Other Annoyances filter, Fanboy's Social Blocking List

### Issue Details

Steps to reproduce:
1. Have adguard running
2. Use computer as normal. 

### Expected Behavior

App window only opens when specifically opened by user (through app icon, safari icon, menu bar icon, etc.)

### Actual Behavior

Seemingly randomly app window will open and redirect focus from whatever is happening to it.

**Comment by maximtop** [comment]
Update to the latest version v1.11.16, it should be fixed there.
