### ISSUE TITLE
Persian Language filter not working properly on MacOS

### ISSUE THREAD

**Issue by asto-ms** [AdguardTeam/AdGuardMiniForMac#939]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.16

### Environment

```markdown
- OS: Sonoma 14.1.2
- Safari version:17.1.2

This issue seems to be only happening in MacOS, as adguard with the same settings and filters block all the persian ads on my iOS device
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, Iranian filter

### Issue Details

Steps to reproduce:
1. Add the following filters on MacOS adguard: adguard base + Persian Blocker
2. go to a random persian website: https://donya-e-eqtesad.com/
3. No persian ads are blocked

### Expected Behavior

Expected to see persian ads to be removed

### Actual Behavior

All persian ads are still showing on the webpage. This problem is not happening on iOS and is only present in MacOS

### Screenshots

<img width="931" alt="Screenshot 2023-12-12 at 11 07 24 AM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/143348971/706f2a51-bcd6-4e21-ab75-127fee78feb1">
<img width="817" alt="Screenshot 2023-12-12 at 11 07 41 AM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/143348971/d811af17-d392-46ea-ac65-3bba7d78856f">
<img width="1276" alt="Screenshot 2023-12-12 at 11 08 08 AM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/143348971/b24ff5f7-0c86-4eee-b59b-f9f1f8285616">

**Comment by alexx7311** [comment]
@asto-ms Hello! Please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
