### ISSUE TITLE
Please help me use the pinterest bookmarklet on safari

### ISSUE THREAD

**Issue by veitch123** [AdguardTeam/AdGuardMiniForMac#946]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.16

### Environment

```markdown
- OS: 14.2.1
- Safari version: 17.2.1
```

### Issue Details

Steps to reproduce:
1. Add pinterest bookmarkelet from [here](https://gist.github.com/kentbrew/142cb69124223a5d0f3b3fd7fc2c6bd0)
2. Press it
3. Nothing happens

### Expected Behavior

It should open up pinterest and allow me to add what's on the page to it. 

### Actual Behavior

Zilch. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Sometimes it says "ContentSecurityPolicyError!" 
It works with adguard paused

**Comment by alexx7311** [comment]
@veitch123 Hello! Please disable Social Media filter or you can use `@@||pinterest.com^$domain=example.org` user rule (where you can substitute **example.org** for any domain you need).
