### ISSUE TITLE
YouTube is slow when AdGuard For Safari is enabled

### ISSUE THREAD

**Issue by fidget05** [AdguardTeam/AdGuardMiniForMac#950]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.16

### Environment

```markdown
- OS:Monterey
- Safari version: 12.7.3
```

### Issue Details

Steps to reproduce:
1. Why is YouTube SO slow after your update??????
2.
3.

### Expected Behavior

e

### Actual Behavior

e

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
see

### Additional Information

dwk;ejifrjifjfopfrpo. fix it

**Comment by Hildebrand** [comment]
yes, same here. Unusable this way. On MacOS Ventura 13.6.4 (22G513). Safari 17.3 (18617.2.4.11.9, 18617).

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/AdGuardForSafari/issues/947
