### ISSUE TITLE
Ynet.co.il video ads

### ISSUE THREAD

**Issue by danygle** [AdguardTeam/AdGuardMiniForMac#955]
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 1.11.16 (build 324, CT 2.0.44)

### Environment

```markdown
- OS: Sonoma 14.3 (23D56)
- Safari version: 17.3 (19617.2.4.11.8)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Spanish/Portuguese filter, EasyList Hebrew

### Issue Details

Steps to reproduce:
1. Go to https://www.ynet.co.il/news/article/rkyr2clqt#autoplay
2. Click on any video.

### Expected Behavior

Block the ads

### Actual Behavior

You won't see anything but the ad plays and you hear the sound

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@danygle Hello! Please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
