### ISSUE TITLE
How to disable AdGuard Legacy assistant

### ISSUE THREAD

**Issue by bikermikem** [AdguardTeam/AdGuardMiniForMac#960]
### Issue Details

The Adguard Logo in the lower right hand corner makes it difficult to select the Google Map Street View button that you drag to a point on the map.

### Proposed solution

An Option to hide it.  Why it's there is beyond me as there are two logos in tools bar to begin with.

**Comment by alexx7311** [comment]
@bikermikem Hello! You're probably reffering to AdGuard Legacy Assistant. You can disable it by going to AdGuard Preferences > Assistant > and unchecking *Use the legacy non-browser extension version*

<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/e143ee88-2111-4991-8b0a-39140a9a3123)

</details>
