### ISSUE TITLE
AdGuard for Safari Filters Issue - Not All The Rules Are Applying

### ISSUE THREAD

**Issue by tamasfilkor** [AdguardTeam/AdGuardMiniForMac#961]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.16

### Environment

```markdown
- OS: macOS Sonoma Version 14.3.1
- Safari version: 17.3.1
```

### Issue Details

I have encountered an issue where the custom user rules in AdGuard do not seem to be applying. Additionally, filters like Peter Lowe's Blocklist, Fanboy's Annoyances, Online Malicious URL Blocklist, and a custom filter for "Actually Legitimate URL Shortener Tool" are not being applied.

Steps to Reproduce:
1. Open AdGuard for Safari.
2. Navigate to the "Filters" tab.
3. Add a custom User rule using the syntax provided in the [filter rules documentation](https://adguard.com/kb/general/ad-filtering/create-own-filters/). For example:
  ```
  *$third-party
  ||google.com^$third-party
  $third-party=goole.com
  ```
4. Enable Peter Lowe's Blocklist filter, Fanboy's Annoyances, Online Malicious URL Blocklist, and ["Actually Legitimate URL Shortener Tool" custom filter](raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt).
5. Visit a website where the custom rules and filters should take effect.

### Expected Behavior

The custom user rules and selected filters should be applied as configured in the AdGuard settings.

### Actual Behavior

Only the following filters are detected (tested on [browserleaks.com](https://browserleaks.com)):
- AdGuard Base
- AdGuard Tracking Protection
- EasyList
- EasyPrivacy

### Screenshots

<details><summary>Filter settings:</summary>

<img width="888" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/37575454/340379de-c8f0-4a61-bb0d-bac83f93a339">

</details>
<details><summary>User rules:</summary>

<img width="884" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/37575454/e7a0d9aa-cfdf-4aba-948c-496418068fd1">

</details>
<details><summary>Browserleaks.com's content filters result:</summary>

<img width="995" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/37575454/a22237aa-1bf1-4c4f-9db3-eaee8cf1e668">

</details>
<details><summary>Browserleaks.com's JavaScript detection:</summary>

<img width="310" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/37575454/3291a0b3-76d6-4e1d-8526-5c9eff961bc3">

</details>

### Additional Information

In comparison, a similar setup with uBlock Origin in Firefox displays the expected filters on browserleaks.com.
<details><summary>Firefox's content filters result:</summary>

<img width="991" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/37575454/da13f4d5-d8e4-4c87-8189-acffe249613f">

</details>
<details><summary>Firefox's JavaScript detection:</summary>

<img width="338" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/37575454/0ab7f10e-77ac-4c1c-8248-b57779207687">

</details>

**Comment by alexx7311** [comment]
@tamasfilkor Hello! The way this website determines the presence of filters isn't exactly reliable. It sends a request and sees if it is blocked or not, and then displays the filter that the rule might be in. The problem is that multiple blocking rules may be in the same filter, or the site may not know the filter the rule is in.

To block third-party scripts on this website, you can try the `||permissions.browserleaks.org^$third-party` rule.
