### ISSUE TITLE
Ads on Deezer

### ISSUE THREAD

**Issue by steeley** [AdguardTeam/AdGuardMiniForMac#966]
### AdGuard Extension version

safari 1.11.16

### Browser version

safari 17.2.1

### OS version

osx 13.6.3

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

adverts play on Deezer.

### Expected Behavior

adguard used to block these ok

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@steeley Hello! Please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
