### ISSUE TITLE
ygosu.com website is not displaying correctly

### ISSUE THREAD

**Issue by noahkim123** [AdguardTeam/AdGuardMiniForMac#969]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.17

### Environment

```markdown
- OS: Mac OS
- Safari version: latest
```

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
When Basefilter is enabled, it occurs when accessing websites in Safari.
Website URL :  ygosu.com

### Expected Behavior

![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/163825225/f32ca928-f531-4b1f-b645-c38c7011ff58)

### Actual Behavior

![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/163825225/dd5172d2-f935-4076-900c-14abff27575a)

### Screenshots

<details><summary>Screenshot 1:Web page screenshot</summary>

![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/163825225/9d5f2187-da31-4e00-9351-7e6bf18cfdb1)

</details>

**Comment by alexx7311** [comment]
@noahkim123 Hello! Please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
