### ISSUE TITLE
Ads on Spotify website in Safari

### ISSUE THREAD

**Issue by dogauto** [AdguardTeam/AdGuardMiniForMac#973]
hi I am using Mac m1 ! I love ad guard from many days ! but resell I am checking on to it that when I was using Spotify ! I was not able to filter it out plz!  patch it as soon as you can ! 
thanks

**Comment by alexx7311** [comment]
@dogauto Hello! Please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
