### ISSUE TITLE
Обращение 900523

### ISSUE THREAD

**Issue by Gaspardow** [AdguardTeam/AdGuardMiniForMac#981]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.17 (build 329, CT 2.0.44)

### Environment

```markdown
- OS:macOS 14.4.1
- Safari version: 17.4.1
```

### Issue Details

Обращение 900523

### Actual Behavior

Обращение 900523

### Screenshots

<img width="1404" alt="Снимок экрана 2024-05-01 в 19 57 51" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/168732549/e5a9b42d-4edb-4567-8e4c-271afbd329ff">

### Additional Information

Номер обращения 900523

**Comment by alexx7311** [comment]
@Gaspardow Hello! Please report this website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
