### ISSUE TITLE
Not blocking ads

### ISSUE THREAD

**Issue by stewmair** [AdguardTeam/AdGuardMiniForMac#989]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.18

### Environment

```markdown
- OS:Ventura 13.6.7
- Safari version:17.5
```

### What filters do you have enabled?

No filters

### Issue Details

Steps to reproduce:
1.Set up Adguard
2.Restart computer
3.No blocking

### Expected Behavior

Ads blocked

### Actual Behavior

No blocking

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@stewmair Any updates?
