### ISSUE TITLE
Adguard is not working in Safari Web Apps

### ISSUE THREAD

**Issue by sk-911** [AdguardTeam/AdGuardMiniForMac#996]
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [ ] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 1.11.18 (build 332, CT 2.0.44)

### Environment

```markdown
- OS: Mac OS Sequoia
- Safari version: Version 18.0 (20619.1.18.11.1)
```

### Issue Details

Steps to reproduce:
1. File > Add to Dock
2. Adguard is not enabled on web app

<img width="742" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/166317544/8ca7f1d1-c4b4-4c31-9213-ae4d445b112a">

### Actual Behavior

<img width="742" alt="image" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/166317544/6a5e32d9-bbe8-46cd-97b2-972ff411a08a">

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/AdGuardForSafari/issues/872
