### ISSUE TITLE
adblocker popup not blocked

### ISSUE THREAD

**Issue by gwargo1** [AdguardTeam/AdGuardMiniForMac#999]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 1.11.18 (build 332, CT 2.0.44)

### Environment

```markdown
- OS:Ventura 13.6.7
- Safari version: Version 17.5 (18618.2.12.111.5, 18618)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, Filter unblocking search ads and self-promotion, EasyPrivacy, AdBlockID, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Peter Lowe's Blocklist, Xfiles, Adblock Warning Removal List, Online Malicious URL Blocklist, RU AdList - Counters, ABPVN List, Fanboy's Enhanced Tracking List, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Polish GDPR-Cookies Filters, Estonian List, CJX's Annoyances List, Polish Social Filters, Fanboy's Anti-Facebook List, List-KR, xinggsf, I don't care about cookies, EasyList Spanish, KAD - Anti-Scam, Adblock List for Finland, ROLIST2, Fanboy's Anti-thirdparty Fonts, NoCoin Filter List

### Issue Details

Steps to reproduce:
1. just loading various webpages such as Deadline
2.
3.

### Expected Behavior

hopefully a simple bypass, this just started within the last few days

### Actual Behavior

when I go to a webpage, the disable adblocker popup loads & have to either try & whitelist a site, which fails, or hopefully it has a click to continue option

### Screenshots

<details><summary>Screenshot 1:</summary>
<img width="2248" alt="Screenshot 2024-07-06 at 4 09 19 PM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/174909806/353e2efa-a490-4482-ae18-52f1a89a1c05">

</details>

**Comment by alexx7311** [comment]
@gwargo1 Hello! Please update the filters in AdGuard for Safari and [clean cookies](https://www.macworld.com/article/670948/how-to-clear-safaris-cache-and-cookies-on-mac.html) in Safari browser. 

If it didn't help please report these website via the extension popup. 
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/6d10a710-b329-4278-957a-4ecd590600a7)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
